// GENERATED by tool/comic/gen_layout_dart.py aus tool/comic/folge01_layout.json.
// Nicht von Hand ändern — Layout-Datei ändern und neu erzeugen (INV-14).

/// p01 quer: みなみまち駅
const List<Map<String, double>> f01HitQuerP01B0 = [
  {'x': 0.06, 'y': 0.12},
  {'x': 0.4, 'y': 0.12},
  {'x': 0.4, 'y': 0.26},
  {'x': 0.06, 'y': 0.26},
];

/// p01 hoch: みなみまち駅
const List<Map<String, double>> f01HitHochP01B0 = [
  {'x': 0.1, 'y': 0.06},
  {'x': 0.64, 'y': 0.06},
  {'x': 0.64, 'y': 0.15},
  {'x': 0.1, 'y': 0.15},
];

/// p03 quer: あめ！あめ！
const List<Map<String, double>> f01HitQuerP03B0 = [
  {'x': 0.06, 'y': 0.12},
  {'x': 0.38, 'y': 0.12},
  {'x': 0.38, 'y': 0.25},
  {'x': 0.06, 'y': 0.25},
];

/// p03 quer: あめ、あめ… さむい、さむい
const List<Map<String, double>> f01HitQuerP03B1 = [
  {'x': 0.57, 'y': 0.12},
  {'x': 0.97, 'y': 0.12},
  {'x': 0.97, 'y': 0.27},
  {'x': 0.57, 'y': 0.27},
];

/// p03 hoch: あめ！あめ！
const List<Map<String, double>> f01HitHochP03B0 = [
  {'x': 0.1, 'y': 0.09},
  {'x': 0.62, 'y': 0.09},
  {'x': 0.62, 'y': 0.16},
  {'x': 0.1, 'y': 0.16},
];

/// p03 hoch: あめ、あめ… さむい、さむい
const List<Map<String, double>> f01HitHochP03B1 = [
  {'x': 0.16, 'y': 0.18},
  {'x': 0.88, 'y': 0.18},
  {'x': 0.88, 'y': 0.27},
  {'x': 0.16, 'y': 0.27},
];

/// p04 quer: 傘
const List<Map<String, double>> f01HitQuerP04B0 = [
  {'x': 0.34, 'y': 0.26},
  {'x': 0.48, 'y': 0.26},
  {'x': 0.48, 'y': 0.43},
  {'x': 0.34, 'y': 0.43},
];

/// p04 quer: …あめ
const List<Map<String, double>> f01HitQuerP04B1 = [
  {'x': 0.6, 'y': 0.12},
  {'x': 0.86, 'y': 0.12},
  {'x': 0.86, 'y': 0.24},
  {'x': 0.6, 'y': 0.24},
];

/// p04 hoch: 傘
const List<Map<String, double>> f01HitHochP04B0 = [
  {'x': 0.12, 'y': 0.36},
  {'x': 0.38, 'y': 0.36},
  {'x': 0.38, 'y': 0.46},
  {'x': 0.12, 'y': 0.46},
];

/// p04 hoch: …あめ
const List<Map<String, double>> f01HitHochP04B1 = [
  {'x': 0.5, 'y': 0.08},
  {'x': 0.88, 'y': 0.08},
  {'x': 0.88, 'y': 0.15},
  {'x': 0.5, 'y': 0.15},
];

/// p05 quer: あめ、あめ！
const List<Map<String, double>> f01HitQuerP05B0 = [
  {'x': 0.66, 'y': 0.1},
  {'x': 0.96, 'y': 0.1},
  {'x': 0.96, 'y': 0.22},
  {'x': 0.66, 'y': 0.22},
];

/// p05 quer: これ？かさ？みせ！
const List<Map<String, double>> f01HitQuerP05B1 = [
  {'x': 0.415, 'y': 0.11},
  {'x': 0.655, 'y': 0.11},
  {'x': 0.655, 'y': 0.23},
  {'x': 0.415, 'y': 0.23},
];

/// p05 quer: ひとり？
const List<Map<String, double>> f01HitQuerP05B2 = [
  {'x': 0.83, 'y': 0.26},
  {'x': 0.98, 'y': 0.26},
  {'x': 0.98, 'y': 0.36},
  {'x': 0.83, 'y': 0.36},
];

/// p05 quer: …はい。ひとり
const List<Map<String, double>> f01HitQuerP05B3 = [
  {'x': 0.02, 'y': 0.1},
  {'x': 0.28, 'y': 0.1},
  {'x': 0.28, 'y': 0.22},
  {'x': 0.02, 'y': 0.22},
];

/// p05 hoch: あめ、あめ！
const List<Map<String, double>> f01HitHochP05B0 = [
  {'x': 0.44, 'y': 0.18},
  {'x': 0.86, 'y': 0.18},
  {'x': 0.86, 'y': 0.25},
  {'x': 0.44, 'y': 0.25},
];

/// p05 hoch: これ？かさ？みせ！
const List<Map<String, double>> f01HitHochP05B1 = [
  {'x': 0.38, 'y': 0.27},
  {'x': 0.9, 'y': 0.27},
  {'x': 0.9, 'y': 0.34},
  {'x': 0.38, 'y': 0.34},
];

/// p05 hoch: ひとり？
const List<Map<String, double>> f01HitHochP05B2 = [
  {'x': 0.56, 'y': 0.36},
  {'x': 0.86, 'y': 0.36},
  {'x': 0.86, 'y': 0.43},
  {'x': 0.56, 'y': 0.43},
];

/// p05 hoch: …はい。ひとり
const List<Map<String, double>> f01HitHochP05B3 = [
  {'x': 0.1, 'y': 0.09},
  {'x': 0.54, 'y': 0.09},
  {'x': 0.54, 'y': 0.16},
  {'x': 0.1, 'y': 0.16},
];

/// p06 quer: これ、こわれた
const List<Map<String, double>> f01HitQuerP06B0 = [
  {'x': 0.04, 'y': 0.12},
  {'x': 0.34, 'y': 0.12},
  {'x': 0.34, 'y': 0.25},
  {'x': 0.04, 'y': 0.25},
];

/// p06 quer: はい、こわれた、こわれた。だめ、だめ
const List<Map<String, double>> f01HitQuerP06B1 = [
  {'x': 0.58, 'y': 0.12},
  {'x': 0.98, 'y': 0.12},
  {'x': 0.98, 'y': 0.28},
  {'x': 0.58, 'y': 0.28},
];

/// p06 quer: …こわれた…？
const List<Map<String, double>> f01HitQuerP06B2 = [
  {'x': 0.04, 'y': 0.29},
  {'x': 0.36, 'y': 0.29},
  {'x': 0.36, 'y': 0.41},
  {'x': 0.04, 'y': 0.41},
];

/// p06 hoch: これ、こわれた
const List<Map<String, double>> f01HitHochP06B0 = [
  {'x': 0.1, 'y': 0.02},
  {'x': 0.56, 'y': 0.02},
  {'x': 0.56, 'y': 0.09},
  {'x': 0.1, 'y': 0.09},
];

/// p06 hoch: はい、こわれた、こわれた。だめ、だめ
const List<Map<String, double>> f01HitHochP06B1 = [
  {'x': 0.14, 'y': 0.1},
  {'x': 0.9, 'y': 0.1},
  {'x': 0.9, 'y': 0.19},
  {'x': 0.14, 'y': 0.19},
];

/// p06 hoch: …こわれた…？
const List<Map<String, double>> f01HitHochP06B2 = [
  {'x': 0.12, 'y': 0.82},
  {'x': 0.62, 'y': 0.82},
  {'x': 0.62, 'y': 0.9},
  {'x': 0.12, 'y': 0.9},
];

/// p07 quer: はい。かさ。どうぞ
const List<Map<String, double>> f01HitQuerP07B0 = [
  {'x': 0.02, 'y': 0.11},
  {'x': 0.34, 'y': 0.11},
  {'x': 0.34, 'y': 0.23},
  {'x': 0.02, 'y': 0.23},
];

/// p07 quer: え？いくら？いくら？
const List<Map<String, double>> f01HitQuerP07B1 = [
  {'x': 0.6, 'y': 0.11},
  {'x': 0.98, 'y': 0.11},
  {'x': 0.98, 'y': 0.23},
  {'x': 0.6, 'y': 0.23},
];

/// p07 quer: いいえ、いいえ。どうぞ、どうぞ。かさ！
const List<Map<String, double>> f01HitQuerP07B2 = [
  {'x': 0.36, 'y': 0.3},
  {'x': 0.68, 'y': 0.3},
  {'x': 0.68, 'y': 0.44},
  {'x': 0.36, 'y': 0.44},
];

/// p07 quer: …ほんとう？
const List<Map<String, double>> f01HitQuerP07B3 = [
  {'x': 0.7, 'y': 0.62},
  {'x': 0.98, 'y': 0.62},
  {'x': 0.98, 'y': 0.72},
  {'x': 0.7, 'y': 0.72},
];

/// p07 quer: ほんとう。だいじょうぶ、だいじょうぶ
const List<Map<String, double>> f01HitQuerP07B4 = [
  {'x': 0.02, 'y': 0.76},
  {'x': 0.42, 'y': 0.76},
  {'x': 0.42, 'y': 0.89},
  {'x': 0.02, 'y': 0.89},
];

/// p07 hoch: はい。かさ。どうぞ
const List<Map<String, double>> f01HitHochP07B0 = [
  {'x': 0.1, 'y': 0.02},
  {'x': 0.62, 'y': 0.02},
  {'x': 0.62, 'y': 0.09},
  {'x': 0.1, 'y': 0.09},
];

/// p07 hoch: え？いくら？いくら？
const List<Map<String, double>> f01HitHochP07B1 = [
  {'x': 0.38, 'y': 0.1},
  {'x': 0.9, 'y': 0.1},
  {'x': 0.9, 'y': 0.17},
  {'x': 0.38, 'y': 0.17},
];

/// p07 hoch: いいえ、いいえ。どうぞ、どうぞ。かさ！
const List<Map<String, double>> f01HitHochP07B2 = [
  {'x': 0.1, 'y': 0.18},
  {'x': 0.9, 'y': 0.18},
  {'x': 0.9, 'y': 0.28},
  {'x': 0.1, 'y': 0.28},
];

/// p07 hoch: …ほんとう？
const List<Map<String, double>> f01HitHochP07B3 = [
  {'x': 0.46, 'y': 0.8},
  {'x': 0.9, 'y': 0.8},
  {'x': 0.9, 'y': 0.87},
  {'x': 0.46, 'y': 0.87},
];

/// p07 hoch: ほんとう。だいじょうぶ、だいじょうぶ
const List<Map<String, double>> f01HitHochP07B4 = [
  {'x': 0.1, 'y': 0.875},
  {'x': 0.9, 'y': 0.875},
  {'x': 0.9, 'y': 0.985},
  {'x': 0.1, 'y': 0.985},
];

/// p08 quer: はいはい
const List<Map<String, double>> f01HitQuerP08B0 = [
  {'x': 0.06, 'y': 0.14},
  {'x': 0.3, 'y': 0.14},
  {'x': 0.3, 'y': 0.26},
  {'x': 0.06, 'y': 0.26},
];

/// p08 quer: ありがとう… すみません… あめ… かさ… いいえ… だいじょうぶ… えき… みせ…
const List<Map<String, double>> f01HitQuerP08B1 = [
  {'x': 0.03, 'y': 0.36},
  {'x': 0.45, 'y': 0.36},
  {'x': 0.45, 'y': 0.62},
  {'x': 0.03, 'y': 0.62},
];

/// p08 hoch: はいはい
const List<Map<String, double>> f01HitHochP08B0 = [
  {'x': 0.1, 'y': 0.05},
  {'x': 0.46, 'y': 0.05},
  {'x': 0.46, 'y': 0.12},
  {'x': 0.1, 'y': 0.12},
];

/// p08 hoch: ありがとう… すみません… あめ… かさ… いいえ… だいじょうぶ… えき… みせ…
const List<Map<String, double>> f01HitHochP08B1 = [
  {'x': 0.1, 'y': 0.73},
  {'x': 0.9, 'y': 0.73},
  {'x': 0.9, 'y': 0.87},
  {'x': 0.1, 'y': 0.87},
];

/// p09 quer: あめやどり
const List<Map<String, double>> f01HitQuerP09B0 = [
  {'x': 0.08, 'y': 0.12},
  {'x': 0.38, 'y': 0.12},
  {'x': 0.38, 'y': 0.25},
  {'x': 0.08, 'y': 0.25},
];

/// p09 quer: ここ…？あめ…やどり？
const List<Map<String, double>> f01HitQuerP09B1 = [
  {'x': 0.58, 'y': 0.42},
  {'x': 0.99, 'y': 0.42},
  {'x': 0.99, 'y': 0.56},
  {'x': 0.58, 'y': 0.56},
];

/// p09 hoch: あめやどり
const List<Map<String, double>> f01HitHochP09B0 = [
  {'x': 0.1, 'y': 0.03},
  {'x': 0.56, 'y': 0.03},
  {'x': 0.56, 'y': 0.11},
  {'x': 0.1, 'y': 0.11},
];

/// p09 hoch: ここ…？あめ…やどり？
const List<Map<String, double>> f01HitHochP09B1 = [
  {'x': 0.12, 'y': 0.39},
  {'x': 0.88, 'y': 0.39},
  {'x': 0.88, 'y': 0.47},
  {'x': 0.12, 'y': 0.47},
];

/// p10 quer: ここ…
const List<Map<String, double>> f01HitQuerP10B0 = [
  {'x': 0.1, 'y': 0.2},
  {'x': 0.36, 'y': 0.2},
  {'x': 0.36, 'y': 0.32},
  {'x': 0.1, 'y': 0.32},
];

/// p10 hoch: ここ…
const List<Map<String, double>> f01HitHochP10B0 = [
  {'x': 0.1, 'y': 0.03},
  {'x': 0.4, 'y': 0.03},
  {'x': 0.4, 'y': 0.1},
  {'x': 0.1, 'y': 0.1},
];
