// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

double initTokenizer() => RustLib.instance.api.crateApiSimpleInitTokenizer();

BenchmarkResult benchmarkBatch({required List<String> sentences}) =>
    RustLib.instance.api.crateApiSimpleBenchmarkBatch(sentences: sentences);

class BenchmarkResult {
  final int sentenceCount;
  final double totalTokenizeMs;
  final Float64List perSentenceMs;
  final int totalTokens;

  const BenchmarkResult({
    required this.sentenceCount,
    required this.totalTokenizeMs,
    required this.perSentenceMs,
    required this.totalTokens,
  });

  @override
  int get hashCode =>
      sentenceCount.hashCode ^
      totalTokenizeMs.hashCode ^
      perSentenceMs.hashCode ^
      totalTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BenchmarkResult &&
          runtimeType == other.runtimeType &&
          sentenceCount == other.sentenceCount &&
          totalTokenizeMs == other.totalTokenizeMs &&
          perSentenceMs == other.perSentenceMs &&
          totalTokens == other.totalTokens;
}
