class KanjiEntry {
  final String kanji;
  final String onyomi;
  final String kunyomi;
  final String meaningDe;
  final String meaningEn;
  final int strokeCount;
  final String jlpt;
  final String svgAssetPath;
  final List<String> examples;
  final List<String> exampleReadings;
  final List<String> exampleMeanings;
  final int lessonUnlock;

  const KanjiEntry({
    required this.kanji,
    required this.onyomi,
    required this.kunyomi,
    required this.meaningDe,
    required this.meaningEn,
    required this.strokeCount,
    this.jlpt = 'N5',
    this.svgAssetPath = '',
    this.examples = const [],
    this.exampleReadings = const [],
    this.exampleMeanings = const [],
    this.lessonUnlock = 1,
  });

  String get cardId => 'kanji_$kanji';
}

const List<KanjiEntry> kanjiN5 = [
  KanjiEntry(
    kanji: '日', onyomi: 'ニチ・ジツ', kunyomi: 'ひ・か',
    meaningDe: 'Sonne, Tag', meaningEn: 'sun, day', strokeCount: 4,
    svgAssetPath: 'assets/kanji_svg/65e5.svg',
    examples: ['日本語', '毎日', '今日'],
    exampleReadings: ['にほんご', 'まいにち', 'きょう'],
    exampleMeanings: ['Japanisch', 'jeden Tag', 'heute'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '月', onyomi: 'ゲツ・ガツ', kunyomi: 'つき',
    meaningDe: 'Mond, Monat', meaningEn: 'moon, month', strokeCount: 4,
    svgAssetPath: 'assets/kanji_svg/6708.svg',
    examples: ['一月', '月曜日', 'お月さま'],
    exampleReadings: ['いちがつ', 'げつようび', 'おつきさま'],
    exampleMeanings: ['Januar', 'Montag', 'Mond (höflich)'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '火', onyomi: 'カ', kunyomi: 'ひ',
    meaningDe: 'Feuer', meaningEn: 'fire', strokeCount: 4,
    svgAssetPath: 'assets/kanji_svg/706b.svg',
    examples: ['火曜日', '花火'],
    exampleReadings: ['かようび', 'はなび'],
    exampleMeanings: ['Dienstag', 'Feuerwerk'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '水', onyomi: 'スイ', kunyomi: 'みず',
    meaningDe: 'Wasser', meaningEn: 'water', strokeCount: 4,
    svgAssetPath: 'assets/kanji_svg/6c34.svg',
    examples: ['水曜日', '水泳', 'みず'],
    exampleReadings: ['すいようび', 'すいえい', 'みず'],
    exampleMeanings: ['Mittwoch', 'Schwimmen', 'Wasser'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '木', onyomi: 'モク・ボク', kunyomi: 'き',
    meaningDe: 'Baum, Holz', meaningEn: 'tree, wood', strokeCount: 4,
    svgAssetPath: 'assets/kanji_svg/6728.svg',
    examples: ['木曜日', '木材', '木'],
    exampleReadings: ['もくようび', 'もくざい', 'き'],
    exampleMeanings: ['Donnerstag', 'Holzmaterial', 'Baum'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '金', onyomi: 'キン・コン', kunyomi: 'かね・かな',
    meaningDe: 'Gold, Geld, Freitag', meaningEn: 'gold, money, Friday', strokeCount: 8,
    svgAssetPath: 'assets/kanji_svg/91d1.svg',
    examples: ['金曜日', 'お金', '金色'],
    exampleReadings: ['きんようび', 'おかね', 'きんいろ'],
    exampleMeanings: ['Freitag', 'Geld', 'Goldfarbe'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '土', onyomi: 'ド・ト', kunyomi: 'つち',
    meaningDe: 'Erde, Boden', meaningEn: 'earth, soil', strokeCount: 3,
    svgAssetPath: 'assets/kanji_svg/571f.svg',
    examples: ['土曜日', '土地'],
    exampleReadings: ['どようび', 'とち'],
    exampleMeanings: ['Samstag', 'Land, Grundstück'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '山', onyomi: 'サン', kunyomi: 'やま',
    meaningDe: 'Berg', meaningEn: 'mountain', strokeCount: 3,
    svgAssetPath: 'assets/kanji_svg/5c71.svg',
    examples: ['富士山', '山道', '山'],
    exampleReadings: ['ふじさん', 'やまみち', 'やま'],
    exampleMeanings: ['Fuji', 'Bergweg', 'Berg'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '川', onyomi: 'セン', kunyomi: 'かわ',
    meaningDe: 'Fluss', meaningEn: 'river', strokeCount: 3,
    svgAssetPath: 'assets/kanji_svg/5ddd.svg',
    examples: ['川', '小川', '川魚'],
    exampleReadings: ['かわ', 'おがわ', 'かわざかな'],
    exampleMeanings: ['Fluss', 'kleiner Bach', 'Flussfisch'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '田', onyomi: 'デン', kunyomi: 'た',
    meaningDe: 'Reisfeld', meaningEn: 'rice field', strokeCount: 5,
    svgAssetPath: 'assets/kanji_svg/7530.svg',
    examples: ['田んぼ', '田舎'],
    exampleReadings: ['たんぼ', 'いなか'],
    exampleMeanings: ['Reisfeld', 'Landschaft, Heimat'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '人', onyomi: 'ジン・ニン', kunyomi: 'ひと',
    meaningDe: 'Person, Mensch', meaningEn: 'person', strokeCount: 2,
    svgAssetPath: 'assets/kanji_svg/4eba.svg',
    examples: ['日本人', '外国人', '人'],
    exampleReadings: ['にほんじん', 'がいこくじん', 'ひと'],
    exampleMeanings: ['Japaner', 'Ausländer', 'Person'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '口', onyomi: 'コウ・ク', kunyomi: 'くち',
    meaningDe: 'Mund', meaningEn: 'mouth', strokeCount: 3,
    svgAssetPath: 'assets/kanji_svg/53e3.svg',
    examples: ['口', '出口', '入口'],
    exampleReadings: ['くち', 'でぐち', 'いりぐち'],
    exampleMeanings: ['Mund', 'Ausgang', 'Eingang'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '目', onyomi: 'モク・ボク', kunyomi: 'め',
    meaningDe: 'Auge', meaningEn: 'eye', strokeCount: 5,
    svgAssetPath: 'assets/kanji_svg/76ee.svg',
    examples: ['目', '目的', '三つ目'],
    exampleReadings: ['め', 'もくてき', 'みっつめ'],
    exampleMeanings: ['Auge', 'Ziel, Zweck', 'das dritte'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '耳', onyomi: 'ジ', kunyomi: 'みみ',
    meaningDe: 'Ohr', meaningEn: 'ear', strokeCount: 6,
    svgAssetPath: 'assets/kanji_svg/8033.svg',
    examples: ['耳', '耳鼻科'],
    exampleReadings: ['みみ', 'じびか'],
    exampleMeanings: ['Ohr', 'HNO-Arzt'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '手', onyomi: 'シュ', kunyomi: 'て',
    meaningDe: 'Hand', meaningEn: 'hand', strokeCount: 4,
    svgAssetPath: 'assets/kanji_svg/624b.svg',
    examples: ['手', '手紙', '握手'],
    exampleReadings: ['て', 'てがみ', 'あくしゅ'],
    exampleMeanings: ['Hand', 'Brief', 'Handschlag'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '足', onyomi: 'ソク', kunyomi: 'あし・た',
    meaningDe: 'Fuß, Bein', meaningEn: 'foot, leg', strokeCount: 7,
    svgAssetPath: 'assets/kanji_svg/8db3.svg',
    examples: ['足', '足りる'],
    exampleReadings: ['あし', 'たりる'],
    exampleMeanings: ['Fuß/Bein', 'genug sein'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '力', onyomi: 'リョク・リキ', kunyomi: 'ちから',
    meaningDe: 'Kraft, Stärke', meaningEn: 'power, strength', strokeCount: 2,
    svgAssetPath: 'assets/kanji_svg/529b.svg',
    examples: ['力', '努力', '全力'],
    exampleReadings: ['ちから', 'どりょく', 'ぜんりょく'],
    exampleMeanings: ['Kraft', 'Bemühung', 'volle Kraft'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '大', onyomi: 'ダイ・タイ', kunyomi: 'おお',
    meaningDe: 'groß', meaningEn: 'big, large', strokeCount: 3,
    svgAssetPath: 'assets/kanji_svg/5927.svg',
    examples: ['大学', '大きい', '大切'],
    exampleReadings: ['だいがく', 'おおきい', 'たいせつ'],
    exampleMeanings: ['Universität', 'groß', 'wichtig'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '小', onyomi: 'ショウ', kunyomi: 'ちい・こ・お',
    meaningDe: 'klein', meaningEn: 'small, little', strokeCount: 3,
    svgAssetPath: 'assets/kanji_svg/5c0f.svg',
    examples: ['小学校', '小さい', '小鳥'],
    exampleReadings: ['しょうがっこう', 'ちいさい', 'ことり'],
    exampleMeanings: ['Grundschule', 'klein', 'kleiner Vogel'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '中', onyomi: 'チュウ', kunyomi: 'なか',
    meaningDe: 'Mitte, innen', meaningEn: 'middle, inside', strokeCount: 4,
    svgAssetPath: 'assets/kanji_svg/4e2d.svg',
    examples: ['中学校', '中国', '中'],
    exampleReadings: ['ちゅうがっこう', 'ちゅうごく', 'なか'],
    exampleMeanings: ['Mittelschule', 'China', 'Mitte, innen'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '上', onyomi: 'ジョウ', kunyomi: 'うえ・あ',
    meaningDe: 'oben, über', meaningEn: 'above, up', strokeCount: 3,
    svgAssetPath: 'assets/kanji_svg/4e0a.svg',
    examples: ['上手', '上着', '机の上'],
    exampleReadings: ['じょうず', 'うわぎ', 'つくえのうえ'],
    exampleMeanings: ['geschickt', 'Jacke', 'auf dem Tisch'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '下', onyomi: 'カ・ゲ', kunyomi: 'した・さ',
    meaningDe: 'unten, unter', meaningEn: 'below, down', strokeCount: 3,
    svgAssetPath: 'assets/kanji_svg/4e0b.svg',
    examples: ['下手', '地下', 'いす下'],
    exampleReadings: ['へた', 'ちか', 'いすのした'],
    exampleMeanings: ['ungeschickt', 'Untergrund', 'unter dem Stuhl'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '左', onyomi: 'サ', kunyomi: 'ひだり',
    meaningDe: 'links', meaningEn: 'left', strokeCount: 5,
    svgAssetPath: 'assets/kanji_svg/5de6.svg',
    examples: ['左', '左側', '左折'],
    exampleReadings: ['ひだり', 'ひだりがわ', 'させつ'],
    exampleMeanings: ['links', 'linke Seite', 'Links abbiegen'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '右', onyomi: 'ウ・ユウ', kunyomi: 'みぎ',
    meaningDe: 'rechts', meaningEn: 'right', strokeCount: 5,
    svgAssetPath: 'assets/kanji_svg/53f3.svg',
    examples: ['右', '右側', '右折'],
    exampleReadings: ['みぎ', 'みぎがわ', 'うせつ'],
    exampleMeanings: ['rechts', 'rechte Seite', 'Rechts abbiegen'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '先', onyomi: 'セン', kunyomi: 'さき',
    meaningDe: 'vorher, Spitze', meaningEn: 'ahead, previous', strokeCount: 6,
    svgAssetPath: 'assets/kanji_svg/5148.svg',
    examples: ['先生', '先週', '先'],
    exampleReadings: ['せんせい', 'せんしゅう', 'さき'],
    exampleMeanings: ['Lehrer', 'letzte Woche', 'vorher, Spitze'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '生', onyomi: 'セイ・ショウ', kunyomi: 'い・う・は・お・なま',
    meaningDe: 'Leben, geboren', meaningEn: 'life, born', strokeCount: 5,
    svgAssetPath: 'assets/kanji_svg/751f.svg',
    examples: ['学生', '先生', '生まれる'],
    exampleReadings: ['がくせい', 'せんせい', 'うまれる'],
    exampleMeanings: ['Student', 'Lehrer', 'geboren werden'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '学', onyomi: 'ガク', kunyomi: 'まな',
    meaningDe: 'lernen, Studium', meaningEn: 'learning, study', strokeCount: 8,
    svgAssetPath: 'assets/kanji_svg/5b66.svg',
    examples: ['学校', '大学', '学ぶ'],
    exampleReadings: ['がっこう', 'だいがく', 'まなぶ'],
    exampleMeanings: ['Schule', 'Universität', 'lernen'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '校', onyomi: 'コウ', kunyomi: '',
    meaningDe: 'Schule', meaningEn: 'school', strokeCount: 10,
    svgAssetPath: 'assets/kanji_svg/6821.svg',
    examples: ['学校', '校長', '高校'],
    exampleReadings: ['がっこう', 'こうちょう', 'こうこう'],
    exampleMeanings: ['Schule', 'Schulleiter', 'Oberschule'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '本', onyomi: 'ホン', kunyomi: 'もと',
    meaningDe: 'Buch, Ursprung', meaningEn: 'book, origin', strokeCount: 5,
    svgAssetPath: 'assets/kanji_svg/672c.svg',
    examples: ['本', '日本', '本当'],
    exampleReadings: ['ほん', 'にほん', 'ほんとう'],
    exampleMeanings: ['Buch', 'Japan', 'wirklich, wahr'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '文', onyomi: 'ブン・モン', kunyomi: 'ふみ',
    meaningDe: 'Text, Schrift', meaningEn: 'text, sentence', strokeCount: 4,
    svgAssetPath: 'assets/kanji_svg/6587.svg',
    examples: ['文章', '作文', '文字'],
    exampleReadings: ['ぶんしょう', 'さくぶん', 'もじ'],
    exampleMeanings: ['Text, Aufsatz', 'Schulaufsatz', 'Schriftzeichen'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '字', onyomi: 'ジ', kunyomi: 'あざ',
    meaningDe: 'Schriftzeichen', meaningEn: 'character, letter', strokeCount: 6,
    svgAssetPath: 'assets/kanji_svg/5b57.svg',
    examples: ['文字', '漢字', '字'],
    exampleReadings: ['もじ', 'かんじ', 'じ'],
    exampleMeanings: ['Schriftzeichen', 'Kanji', 'Zeichen'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '子', onyomi: 'シ・ス', kunyomi: 'こ',
    meaningDe: 'Kind', meaningEn: 'child', strokeCount: 3,
    svgAssetPath: 'assets/kanji_svg/5b50.svg',
    examples: ['子供', '女子', '男子'],
    exampleReadings: ['こども', 'じょし', 'だんし'],
    exampleMeanings: ['Kind', 'Mädchen/Frau', 'Junge/Mann'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '女', onyomi: 'ジョ・ニョ', kunyomi: 'おんな',
    meaningDe: 'Frau, weiblich', meaningEn: 'woman, female', strokeCount: 3,
    svgAssetPath: 'assets/kanji_svg/5973.svg',
    examples: ['女', '女性', '彼女'],
    exampleReadings: ['おんな', 'じょせい', 'かのじょ'],
    exampleMeanings: ['Frau', 'Frau (formal)', 'sie, Freundin'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '男', onyomi: 'ダン・ナン', kunyomi: 'おとこ',
    meaningDe: 'Mann, männlich', meaningEn: 'man, male', strokeCount: 7,
    svgAssetPath: 'assets/kanji_svg/7537.svg',
    examples: ['男', '男性', '彼'],
    exampleReadings: ['おとこ', 'だんせい', 'かれ'],
    exampleMeanings: ['Mann', 'Mann (formal)', 'er, Freund'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '一', onyomi: 'イチ・イツ', kunyomi: 'ひと',
    meaningDe: 'eins', meaningEn: 'one', strokeCount: 1,
    svgAssetPath: 'assets/kanji_svg/4e00.svg',
    examples: ['一つ', '一月', '一番'],
    exampleReadings: ['ひとつ', 'いちがつ', 'いちばん'],
    exampleMeanings: ['eins', 'Januar', 'Nummer 1, am besten'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '二', onyomi: 'ニ', kunyomi: 'ふた',
    meaningDe: 'zwei', meaningEn: 'two', strokeCount: 2,
    svgAssetPath: 'assets/kanji_svg/4e8c.svg',
    examples: ['二つ', '二月', '二人'],
    exampleReadings: ['ふたつ', 'にがつ', 'ふたり'],
    exampleMeanings: ['zwei', 'Februar', 'zwei Personen'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '三', onyomi: 'サン', kunyomi: 'み',
    meaningDe: 'drei', meaningEn: 'three', strokeCount: 3,
    svgAssetPath: 'assets/kanji_svg/4e09.svg',
    examples: ['三つ', '三月', '三人'],
    exampleReadings: ['みっつ', 'さんがつ', 'さんにん'],
    exampleMeanings: ['drei', 'März', 'drei Personen'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '四', onyomi: 'シ', kunyomi: 'よ・よん',
    meaningDe: 'vier', meaningEn: 'four', strokeCount: 5,
    svgAssetPath: 'assets/kanji_svg/56db.svg',
    examples: ['四つ', '四月', '四人'],
    exampleReadings: ['よっつ', 'しがつ', 'よにん'],
    exampleMeanings: ['vier', 'April', 'vier Personen'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '五', onyomi: 'ゴ', kunyomi: 'いつ',
    meaningDe: 'fünf', meaningEn: 'five', strokeCount: 4,
    svgAssetPath: 'assets/kanji_svg/4e94.svg',
    examples: ['五つ', '五月', '五人'],
    exampleReadings: ['いつつ', 'ごがつ', 'ごにん'],
    exampleMeanings: ['fünf', 'Mai', 'fünf Personen'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '六', onyomi: 'ロク', kunyomi: 'む',
    meaningDe: 'sechs', meaningEn: 'six', strokeCount: 4,
    svgAssetPath: 'assets/kanji_svg/516d.svg',
    examples: ['六つ', '六月'],
    exampleReadings: ['むっつ', 'ろくがつ'],
    exampleMeanings: ['sechs', 'Juni'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '七', onyomi: 'シチ', kunyomi: 'なな',
    meaningDe: 'sieben', meaningEn: 'seven', strokeCount: 2,
    svgAssetPath: 'assets/kanji_svg/4e03.svg',
    examples: ['七つ', '七月', '七夕'],
    exampleReadings: ['ななつ', 'しちがつ', 'たなばた'],
    exampleMeanings: ['sieben', 'Juli', 'Tanabata-Fest'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '八', onyomi: 'ハチ', kunyomi: 'や',
    meaningDe: 'acht', meaningEn: 'eight', strokeCount: 2,
    svgAssetPath: 'assets/kanji_svg/516b.svg',
    examples: ['八つ', '八月', '八百'],
    exampleReadings: ['やっつ', 'はちがつ', 'やおや'],
    exampleMeanings: ['acht', 'August', 'Gemüseladen'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '九', onyomi: 'キュウ・ク', kunyomi: 'ここの',
    meaningDe: 'neun', meaningEn: 'nine', strokeCount: 2,
    svgAssetPath: 'assets/kanji_svg/4e5d.svg',
    examples: ['九つ', '九月'],
    exampleReadings: ['ここのつ', 'くがつ'],
    exampleMeanings: ['neun', 'September'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '十', onyomi: 'ジュウ・ジッ', kunyomi: 'とお',
    meaningDe: 'zehn', meaningEn: 'ten', strokeCount: 2,
    svgAssetPath: 'assets/kanji_svg/5341.svg',
    examples: ['十', '十月', '十分'],
    exampleReadings: ['じゅう', 'じゅうがつ', 'じゅうぶん'],
    exampleMeanings: ['zehn', 'Oktober', 'ausreichend'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '百', onyomi: 'ヒャク', kunyomi: 'もも',
    meaningDe: 'hundert', meaningEn: 'hundred', strokeCount: 6,
    svgAssetPath: 'assets/kanji_svg/767e.svg',
    examples: ['百', '百円', '三百'],
    exampleReadings: ['ひゃく', 'ひゃくえん', 'さんびゃく'],
    exampleMeanings: ['hundert', '100 Yen', 'dreihundert'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '千', onyomi: 'セン', kunyomi: 'ち',
    meaningDe: 'tausend', meaningEn: 'thousand', strokeCount: 3,
    svgAssetPath: 'assets/kanji_svg/5343.svg',
    examples: ['千円', '三千', '千葉'],
    exampleReadings: ['せんえん', 'さんぜん', 'ちば'],
    exampleMeanings: ['1000 Yen', 'dreitausend', 'Chiba'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '年', onyomi: 'ネン', kunyomi: 'とし',
    meaningDe: 'Jahr', meaningEn: 'year', strokeCount: 6,
    svgAssetPath: 'assets/kanji_svg/5e74.svg',
    examples: ['今年', '来年', '年'],
    exampleReadings: ['ことし', 'らいねん', 'とし'],
    exampleMeanings: ['dieses Jahr', 'nächstes Jahr', 'Jahr'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '時', onyomi: 'ジ', kunyomi: 'とき',
    meaningDe: 'Zeit, Stunde', meaningEn: 'time, hour', strokeCount: 10,
    svgAssetPath: 'assets/kanji_svg/6642.svg',
    examples: ['時間', '何時', '時々'],
    exampleReadings: ['じかん', 'なんじ', 'ときどき'],
    exampleMeanings: ['Zeit', 'wieviel Uhr', 'manchmal'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '国', onyomi: 'コク', kunyomi: 'くに',
    meaningDe: 'Land, Nation', meaningEn: 'country, nation', strokeCount: 8,
    svgAssetPath: 'assets/kanji_svg/56fd.svg',
    examples: ['日本国', '外国', '国語'],
    exampleReadings: ['にほんこく', 'がいこく', 'こくご'],
    exampleMeanings: ['Japan (formal)', 'Ausland', 'Japanisch (Fach)'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '語', onyomi: 'ゴ', kunyomi: 'かた',
    meaningDe: 'Sprache, Wort', meaningEn: 'language, word', strokeCount: 14,
    svgAssetPath: 'assets/kanji_svg/8a9e.svg',
    examples: ['日本語', '英語', '語る'],
    exampleReadings: ['にほんご', 'えいご', 'かたる'],
    exampleMeanings: ['Japanisch', 'Englisch', 'erzählen'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '何', onyomi: 'カ', kunyomi: 'なに・なん',
    meaningDe: 'was, welcher', meaningEn: 'what, which', strokeCount: 7,
    svgAssetPath: 'assets/kanji_svg/4f55.svg',
    examples: ['何', '何時', '何語'],
    exampleReadings: ['なに', 'なんじ', 'なにご'],
    exampleMeanings: ['was', 'wieviel Uhr', 'welche Sprache'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '見', onyomi: 'ケン', kunyomi: 'み',
    meaningDe: 'sehen, schauen', meaningEn: 'see, look', strokeCount: 7,
    svgAssetPath: 'assets/kanji_svg/898b.svg',
    examples: ['見る', '見物', '見学'],
    exampleReadings: ['みる', 'けんぶつ', 'けんがく'],
    exampleMeanings: ['sehen', 'Besichtigung', 'Studienbesuch'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '行', onyomi: 'コウ・ギョウ', kunyomi: 'い・ゆ・おこな',
    meaningDe: 'gehen', meaningEn: 'go, conduct', strokeCount: 6,
    svgAssetPath: 'assets/kanji_svg/884c.svg',
    examples: ['行く', '旅行', '行動'],
    exampleReadings: ['いく', 'りょこう', 'こうどう'],
    exampleMeanings: ['gehen', 'Reise', 'Handlung'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '来', onyomi: 'ライ', kunyomi: 'く・き・こ',
    meaningDe: 'kommen', meaningEn: 'come', strokeCount: 7,
    svgAssetPath: 'assets/kanji_svg/6765.svg',
    examples: ['来る', '来年', '来週'],
    exampleReadings: ['くる', 'らいねん', 'らいしゅう'],
    exampleMeanings: ['kommen', 'nächstes Jahr', 'nächste Woche'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '食', onyomi: 'ショク', kunyomi: 'た・く',
    meaningDe: 'essen, Nahrung', meaningEn: 'eat, food', strokeCount: 9,
    svgAssetPath: 'assets/kanji_svg/98df.svg',
    examples: ['食べる', '食事', '朝食'],
    exampleReadings: ['たべる', 'しょくじ', 'ちょうしょく'],
    exampleMeanings: ['essen', 'Mahlzeit', 'Frühstück'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '飲', onyomi: 'イン', kunyomi: 'の',
    meaningDe: 'trinken', meaningEn: 'drink', strokeCount: 12,
    svgAssetPath: 'assets/kanji_svg/98f2.svg',
    examples: ['飲む', '飲み物', '飲食'],
    exampleReadings: ['のむ', 'のみもの', 'いんしょく'],
    exampleMeanings: ['trinken', 'Getränk', 'Essen und Trinken'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '書', onyomi: 'ショ', kunyomi: 'か',
    meaningDe: 'schreiben', meaningEn: 'write', strokeCount: 10,
    svgAssetPath: 'assets/kanji_svg/66f8.svg',
    examples: ['書く', '教科書', '図書館'],
    exampleReadings: ['かく', 'きょうかしょ', 'としょかん'],
    exampleMeanings: ['schreiben', 'Schulbuch', 'Bibliothek'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '読', onyomi: 'ドク・トク', kunyomi: 'よ',
    meaningDe: 'lesen', meaningEn: 'read', strokeCount: 14,
    svgAssetPath: 'assets/kanji_svg/8aad.svg',
    examples: ['読む', '読書', '読み方'],
    exampleReadings: ['よむ', 'どくしょ', 'よみかた'],
    exampleMeanings: ['lesen', 'Lesen (Hobby)', 'Lesart'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '聞', onyomi: 'ブン・モン', kunyomi: 'き',
    meaningDe: 'hören, fragen', meaningEn: 'hear, ask', strokeCount: 14,
    svgAssetPath: 'assets/kanji_svg/805e.svg',
    examples: ['聞く', '聞き取り', '新聞'],
    exampleReadings: ['きく', 'ききとり', 'しんぶん'],
    exampleMeanings: ['hören/fragen', 'Hörverständnis', 'Zeitung'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '話', onyomi: 'ワ', kunyomi: 'はな・はなし',
    meaningDe: 'sprechen, Geschichte', meaningEn: 'speak, story', strokeCount: 13,
    svgAssetPath: 'assets/kanji_svg/8a71.svg',
    examples: ['話す', '電話', '話題'],
    exampleReadings: ['はなす', 'でんわ', 'わだい'],
    exampleMeanings: ['sprechen', 'Telefon', 'Thema'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '気', onyomi: 'キ・ケ', kunyomi: '',
    meaningDe: 'Geist, Luft, Energie', meaningEn: 'spirit, air, energy', strokeCount: 6,
    svgAssetPath: 'assets/kanji_svg/6c17.svg',
    examples: ['気', '天気', '元気'],
    exampleReadings: ['き', 'てんき', 'げんき'],
    exampleMeanings: ['Geist', 'Wetter', 'gesund, munter'],
    lessonUnlock: 1,
  ),
  KanjiEntry(
    kanji: '心', onyomi: 'シン', kunyomi: 'こころ',
    meaningDe: 'Herz, Gemüt', meaningEn: 'heart, mind', strokeCount: 4,
    svgAssetPath: 'assets/kanji_svg/5fc3.svg',
    examples: ['心', '安心', '心配'],
    exampleReadings: ['こころ', 'あんしん', 'しんぱい'],
    exampleMeanings: ['Herz/Gemüt', 'beruhigt', 'Sorge'],
    lessonUnlock: 1,
  ),
];

// N4-Kanji (Auswahl, wird in Phase 3 erweitert)
const List<KanjiEntry> kanjiN4 = [];

List<KanjiEntry> get allKanji => kanjiN5 + kanjiN4;
