#!/usr/bin/env python3
"""Erzeugt lib/features/story/episodes/folge_01_layout.g.dart aus folge01_layout.json (INV-14).
Aufruf im Repo-Wurzelverzeichnis: python3 tool/comic/gen_layout_dart.py"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
LAYOUT = os.path.join(HERE, "folge01_layout.json")
OUT = "lib/features/story/episodes/folge_01_layout.g.dart"


def const_name(pid, fmt, i):
    return "f01Hit%s%sB%d" % ("Quer" if fmt == "quer" else "Hoch", pid.capitalize(), i)


def points(rect):
    x, y, w, h = rect
    return [(x, y), (x + w, y), (x + w, y + h), (x, y + h)]


def main():
    with open(LAYOUT, encoding="utf-8") as f:
        layout = json.load(f)
    lines = ["// GENERATED by tool/comic/gen_layout_dart.py aus tool/comic/folge01_layout.json.",
             "// Nicht von Hand ändern — Layout-Datei ändern und neu erzeugen (INV-14).", ""]
    for pid, formats in layout["panels"].items():
        for fmt, spec in formats.items():
            for i, b in enumerate(spec.get("bubbles", [])):
                pts = ", ".join("{'x': %s, 'y': %s}" % (round(px, 4), round(py, 4)) for px, py in points(b["rect"]))
                lines.append("/// %s %s: %s" % (pid, fmt, b["text"]))
                lines.append("const List<Map<String, double>> %s = [%s];" % (const_name(pid, fmt, i), pts))
                lines.append("")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(OUT)


if __name__ == "__main__":
    main()
