//
// Wortvorrat 800, Liste C: Menschen, Familie, Körper, Befinden.
// Quelle: Plan docs/superpowers/plans/2026-09-18-wortvorrat-800.md, Task 5.

import 'pool_entry.dart';

const List<PoolEntry> vocabPoolJaMenschen = [
  PoolEntry(id: 'lex_ja_hito', kana: 'ひと', written: '人', meaningDe: 'Mensch, Person', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_otoko', kana: 'おとこ', written: '男', meaningDe: 'Mann', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_onna', kana: 'おんな', written: '女', meaningDe: 'Frau', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_otokonoko', kana: 'おとこのこ', written: '男の子', meaningDe: 'Junge', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_onnanoko', kana: 'おんなのこ', written: '女の子', meaningDe: 'Mädchen', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_kodomo', kana: 'こども', written: '子ども', meaningDe: 'Kind', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_otona', kana: 'おとな', written: '大人', meaningDe: 'Erwachsener', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_akachan', kana: 'あかちゃん', written: '赤ちゃん', meaningDe: 'Baby', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_gakusei', kana: 'がくせい', written: '学生', meaningDe: 'Student', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_seito', kana: 'せいと', written: '生徒', meaningDe: 'Schüler', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_sensei', kana: 'せんせい', written: '先生', meaningDe: 'Lehrer', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_tomodachi', kana: 'ともだち', written: '友達', meaningDe: 'Freund', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_kazoku', kana: 'かぞく', written: '家族', meaningDe: 'Familie', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_namae', kana: 'なまえ', written: '名前', meaningDe: 'Name', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_watashi', kana: 'わたし', written: '私', meaningDe: 'ich', pos: PartOfSpeech.pronomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_anata', kana: 'あなた', meaningDe: 'du, Sie', pos: PartOfSpeech.pronomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_kare', kana: 'かれ', written: '彼', meaningDe: 'er', pos: PartOfSpeech.pronomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_kanojo', kana: 'かのじょ', written: '彼女', meaningDe: 'sie', pos: PartOfSpeech.pronomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_minna', kana: 'みんな', meaningDe: 'alle', pos: PartOfSpeech.pronomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_jibun', kana: 'じぶん', written: '自分', meaningDe: 'selbst', pos: PartOfSpeech.pronomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_okyakusan', kana: 'おきゃくさん', written: 'お客さん', meaningDe: 'Gast, Kunde', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_tenin', kana: 'てんいん', written: '店員', meaningDe: 'Verkäufer', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_isha', kana: 'いしゃ', written: '医者', meaningDe: 'Arzt', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_keisatsu', kana: 'けいさつ', written: '警察', meaningDe: 'Polizei', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_gaikokujin', kana: 'がいこくじん', written: '外国人', meaningDe: 'Ausländer', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_nihonjin', kana: 'にほんじん', written: '日本人', meaningDe: 'Japaner', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_doitsujin', kana: 'ドイツじん', written: 'ドイツ人', meaningDe: 'Deutscher', pos: PartOfSpeech.nomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_obaasan', kana: 'おばあさん', meaningDe: 'Großmutter', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_ojiisan', kana: 'おじいさん', meaningDe: 'Großvater', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_okaasan', kana: 'おかあさん', written: 'お母さん', meaningDe: 'Mutter', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_otousan', kana: 'おとうさん', written: 'お父さん', meaningDe: 'Vater', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_haha', kana: 'はは', written: '母', meaningDe: 'meine Mutter', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_chichi', kana: 'ちち', written: '父', meaningDe: 'mein Vater', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_oneesan', kana: 'おねえさん', written: 'お姉さん', meaningDe: 'ältere Schwester', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_oniisan', kana: 'おにいさん', written: 'お兄さん', meaningDe: 'älterer Bruder', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_ane', kana: 'あね', written: '姉', meaningDe: 'meine ältere Schwester', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_ani', kana: 'あに', written: '兄', meaningDe: 'mein älterer Bruder', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_imouto', kana: 'いもうと', written: '妹', meaningDe: 'jüngere Schwester', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_otouto', kana: 'おとうと', written: '弟', meaningDe: 'jüngerer Bruder', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_ojisan', kana: 'おじさん', meaningDe: 'Onkel, älterer Herr', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_obasan', kana: 'おばさん', meaningDe: 'Tante, ältere Dame', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_musume', kana: 'むすめ', written: '娘', meaningDe: 'Tochter', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_musuko', kana: 'むすこ', written: '息子', meaningDe: 'Sohn', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_okusan', kana: 'おくさん', written: '奥さん', meaningDe: 'Ehefrau', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_goshujin', kana: 'ごしゅじん', written: 'ご主人', meaningDe: 'Ehemann', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_ryoushin', kana: 'りょうしん', written: '両親', meaningDe: 'Eltern', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_kyoudai', kana: 'きょうだい', written: '兄弟', meaningDe: 'Geschwister', pos: PartOfSpeech.nomen, domain: VocabDomain.familie),
  PoolEntry(id: 'lex_ja_karada', kana: 'からだ', written: '体', meaningDe: 'Körper', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper),
  PoolEntry(id: 'lex_ja_atama', kana: 'あたま', written: '頭', meaningDe: 'Kopf', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper),
  PoolEntry(id: 'lex_ja_kao', kana: 'かお', written: '顔', meaningDe: 'Gesicht', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper),
  PoolEntry(id: 'lex_ja_me', kana: 'め', written: '目', meaningDe: 'Auge', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper),
  PoolEntry(id: 'lex_ja_mimi', kana: 'みみ', written: '耳', meaningDe: 'Ohr', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper),
  PoolEntry(id: 'lex_ja_hana_nose', kana: 'はな', written: '鼻', meaningDe: 'Nase', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper),
  PoolEntry(id: 'lex_ja_kuchi', kana: 'くち', written: '口', meaningDe: 'Mund', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper),
  PoolEntry(id: 'lex_ja_ha', kana: 'は', written: '歯', meaningDe: 'Zahn', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper),
  PoolEntry(id: 'lex_ja_te', kana: 'て', written: '手', meaningDe: 'Hand', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper),
  PoolEntry(id: 'lex_ja_ashi', kana: 'あし', written: '足', meaningDe: 'Fuß, Bein', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper),
  PoolEntry(id: 'lex_ja_yubi', kana: 'ゆび', written: '指', meaningDe: 'Finger', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper),
  PoolEntry(id: 'lex_ja_kami_hair', kana: 'かみ', written: '髪', meaningDe: 'Haar', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper),
  PoolEntry(id: 'lex_ja_onaka', kana: 'おなか', written: 'お腹', meaningDe: 'Bauch', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper),
  PoolEntry(id: 'lex_ja_se', kana: 'せ', written: '背', meaningDe: 'Körpergröße, Rücken', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper),
  PoolEntry(id: 'lex_ja_koe', kana: 'こえ', written: '声', meaningDe: 'Stimme', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper),
  PoolEntry(id: 'lex_ja_chikara', kana: 'ちから', written: '力', meaningDe: 'Kraft', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper),
  PoolEntry(id: 'lex_ja_genki', kana: 'げんき', written: '元気', meaningDe: 'munter, gesund', pos: PartOfSpeech.naAdjektiv, domain: VocabDomain.gefuehl),
  PoolEntry(id: 'lex_ja_byouki', kana: 'びょうき', written: '病気', meaningDe: 'Krankheit', pos: PartOfSpeech.nomen, domain: VocabDomain.gefuehl),
  PoolEntry(id: 'lex_ja_kaze_cold', kana: 'かぜ', written: '風邪', meaningDe: 'Erkältung', pos: PartOfSpeech.nomen, domain: VocabDomain.gefuehl),
  PoolEntry(id: 'lex_ja_kusuri', kana: 'くすり', written: '薬', meaningDe: 'Medizin', pos: PartOfSpeech.nomen, domain: VocabDomain.gefuehl),
  PoolEntry(id: 'lex_ja_netsu', kana: 'ねつ', written: '熱', meaningDe: 'Fieber', pos: PartOfSpeech.nomen, domain: VocabDomain.gefuehl),
  PoolEntry(id: 'lex_ja_kimochi', kana: 'きもち', written: '気持ち', meaningDe: 'Gefühl', pos: PartOfSpeech.nomen, domain: VocabDomain.gefuehl),
  PoolEntry(id: 'lex_ja_shinpai', kana: 'しんぱい', written: '心配', meaningDe: 'Sorge', pos: PartOfSpeech.nomen, domain: VocabDomain.gefuehl),
  PoolEntry(id: 'lex_ja_namida', kana: 'なみだ', written: '涙', meaningDe: 'Träne', pos: PartOfSpeech.nomen, domain: VocabDomain.gefuehl),
];
