//
// Wortvorrat 800, Liste D: Orte, Haus, Verkehr, Natur, Wetter.
// Quelle: Plan docs/superpowers/plans/2026-09-18-wortvorrat-800.md, Task 6.

import 'pool_entry.dart';

const List<PoolEntry> vocabPoolJaOrteWetter = [
  PoolEntry(id: 'lex_ja_koko', kana: 'ここ', meaningDe: 'hier', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen, plannedEpisode: 1, status: PoolStatus.ausgeliefert),
  PoolEntry(id: 'lex_ja_soko', kana: 'そこ', meaningDe: 'dort', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_asoko', kana: 'あそこ', meaningDe: 'dort drüben', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_doko', kana: 'どこ', meaningDe: 'wo', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_migi', kana: 'みぎ', written: '右', meaningDe: 'rechts', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_hidari', kana: 'ひだり', written: '左', meaningDe: 'links', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_mae', kana: 'まえ', written: '前', meaningDe: 'vorne, vorher', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_ushiro', kana: 'うしろ', written: '後ろ', meaningDe: 'hinten', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_ue', kana: 'うえ', written: '上', meaningDe: 'oben', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_shita', kana: 'した', written: '下', meaningDe: 'unten', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_naka', kana: 'なか', written: '中', meaningDe: 'innen, Mitte', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_soto', kana: 'そと', written: '外', meaningDe: 'draußen', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_tonari', kana: 'となり', written: '隣', meaningDe: 'nebenan', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_chikaku', kana: 'ちかく', written: '近く', meaningDe: 'Nähe', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_yoko', kana: 'よこ', written: '横', meaningDe: 'Seite, daneben', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_aida', kana: 'あいだ', written: '間', meaningDe: 'zwischen', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_kita', kana: 'きた', written: '北', meaningDe: 'Norden', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_minami', kana: 'みなみ', written: '南', meaningDe: 'Süden', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_higashi', kana: 'ひがし', written: '東', meaningDe: 'Osten', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_nishi', kana: 'にし', written: '西', meaningDe: 'Westen', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_machi', kana: 'まち', written: '町', meaningDe: 'Stadt, Viertel', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_mura', kana: 'むら', written: '村', meaningDe: 'Dorf', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_kuni', kana: 'くに', written: '国', meaningDe: 'Land', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_michi', kana: 'みち', written: '道', meaningDe: 'Straße, Weg', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_kousaten', kana: 'こうさてん', written: '交差点', meaningDe: 'Kreuzung', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_kado', kana: 'かど', written: '角', meaningDe: 'Ecke', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_hashi_bridge', kana: 'はし', written: '橋', meaningDe: 'Brücke', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_kouen', kana: 'こうえん', written: '公園', meaningDe: 'Park', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_ginkou', kana: 'ぎんこう', written: '銀行', meaningDe: 'Bank (Geld)', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_yuubinkyoku', kana: 'ゆうびんきょく', written: '郵便局', meaningDe: 'Postamt', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_byouin', kana: 'びょういん', written: '病院', meaningDe: 'Krankenhaus', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_gakkou', kana: 'がっこう', written: '学校', meaningDe: 'Schule', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_daigaku', kana: 'だいがく', written: '大学', meaningDe: 'Universität', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_toshokan', kana: 'としょかん', written: '図書館', meaningDe: 'Bibliothek', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_hoteru', kana: 'ホテル', meaningDe: 'Hotel', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_eigakan', kana: 'えいがかん', written: '映画館', meaningDe: 'Kino', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_otera', kana: 'おてら', written: 'お寺', meaningDe: 'Tempel', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_jinja', kana: 'じんじゃ', written: '神社', meaningDe: 'Schrein', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_kaisha', kana: 'かいしゃ', written: '会社', meaningDe: 'Firma', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_shoutengai', kana: 'しょうてんがい', written: '商店街', meaningDe: 'Einkaufsstraße', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_basho', kana: 'ばしょ', written: '場所', meaningDe: 'Ort', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_tokoro', kana: 'ところ', written: '所', meaningDe: 'Stelle, Ort', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_nihon', kana: 'にほん', written: '日本', meaningDe: 'Japan', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_doitsu', kana: 'ドイツ', meaningDe: 'Deutschland', pos: PartOfSpeech.nomen, domain: VocabDomain.orte),
  PoolEntry(id: 'lex_ja_uchi', kana: 'うち', meaningDe: 'Zuhause', pos: PartOfSpeech.nomen, domain: VocabDomain.haus),
  PoolEntry(id: 'lex_ja_ie', kana: 'いえ', written: '家', meaningDe: 'Haus', pos: PartOfSpeech.nomen, domain: VocabDomain.haus),
  PoolEntry(id: 'lex_ja_heya', kana: 'へや', written: '部屋', meaningDe: 'Zimmer', pos: PartOfSpeech.nomen, domain: VocabDomain.haus),
  PoolEntry(id: 'lex_ja_daidokoro', kana: 'だいどころ', written: '台所', meaningDe: 'Küche', pos: PartOfSpeech.nomen, domain: VocabDomain.haus),
  PoolEntry(id: 'lex_ja_ofuro', kana: 'おふろ', written: 'お風呂', meaningDe: 'Bad', pos: PartOfSpeech.nomen, domain: VocabDomain.haus),
  PoolEntry(id: 'lex_ja_toire', kana: 'トイレ', meaningDe: 'Toilette', pos: PartOfSpeech.nomen, domain: VocabDomain.haus),
  PoolEntry(id: 'lex_ja_genkan', kana: 'げんかん', written: '玄関', meaningDe: 'Hauseingang', pos: PartOfSpeech.nomen, domain: VocabDomain.haus),
  PoolEntry(id: 'lex_ja_niwa', kana: 'にわ', written: '庭', meaningDe: 'Garten', pos: PartOfSpeech.nomen, domain: VocabDomain.haus),
  PoolEntry(id: 'lex_ja_mado', kana: 'まど', written: '窓', meaningDe: 'Fenster', pos: PartOfSpeech.nomen, domain: VocabDomain.haus),
  PoolEntry(id: 'lex_ja_doa', kana: 'ドア', meaningDe: 'Tür', pos: PartOfSpeech.nomen, domain: VocabDomain.haus),
  PoolEntry(id: 'lex_ja_kabe', kana: 'かべ', written: '壁', meaningDe: 'Wand', pos: PartOfSpeech.nomen, domain: VocabDomain.haus),
  PoolEntry(id: 'lex_ja_yuka', kana: 'ゆか', written: '床', meaningDe: 'Fußboden', pos: PartOfSpeech.nomen, domain: VocabDomain.haus),
  PoolEntry(id: 'lex_ja_kaidan', kana: 'かいだん', written: '階段', meaningDe: 'Treppe', pos: PartOfSpeech.nomen, domain: VocabDomain.haus),
  PoolEntry(id: 'lex_ja_iriguchi', kana: 'いりぐち', written: '入口', meaningDe: 'Eingang', pos: PartOfSpeech.nomen, domain: VocabDomain.haus),
  PoolEntry(id: 'lex_ja_deguchi', kana: 'でぐち', written: '出口', meaningDe: 'Ausgang', pos: PartOfSpeech.nomen, domain: VocabDomain.haus),
  PoolEntry(id: 'lex_ja_eki', kana: 'えき', written: '駅', meaningDe: 'Bahnhof', pos: PartOfSpeech.nomen, domain: VocabDomain.verkehr, plannedEpisode: 1, status: PoolStatus.ausgeliefert),
  PoolEntry(id: 'lex_ja_densha', kana: 'でんしゃ', written: '電車', meaningDe: 'Zug', pos: PartOfSpeech.nomen, domain: VocabDomain.verkehr),
  PoolEntry(id: 'lex_ja_chikatetsu', kana: 'ちかてつ', written: '地下鉄', meaningDe: 'U-Bahn', pos: PartOfSpeech.nomen, domain: VocabDomain.verkehr),
  PoolEntry(id: 'lex_ja_basu', kana: 'バス', meaningDe: 'Bus', pos: PartOfSpeech.nomen, domain: VocabDomain.verkehr),
  PoolEntry(id: 'lex_ja_takushii', kana: 'タクシー', meaningDe: 'Taxi', pos: PartOfSpeech.nomen, domain: VocabDomain.verkehr),
  PoolEntry(id: 'lex_ja_kuruma', kana: 'くるま', written: '車', meaningDe: 'Auto', pos: PartOfSpeech.nomen, domain: VocabDomain.verkehr),
  PoolEntry(id: 'lex_ja_jitensha', kana: 'じてんしゃ', written: '自転車', meaningDe: 'Fahrrad', pos: PartOfSpeech.nomen, domain: VocabDomain.verkehr),
  PoolEntry(id: 'lex_ja_hikouki', kana: 'ひこうき', written: '飛行機', meaningDe: 'Flugzeug', pos: PartOfSpeech.nomen, domain: VocabDomain.verkehr),
  PoolEntry(id: 'lex_ja_fune', kana: 'ふね', written: '船', meaningDe: 'Schiff', pos: PartOfSpeech.nomen, domain: VocabDomain.verkehr),
  PoolEntry(id: 'lex_ja_kippu', kana: 'きっぷ', written: '切符', meaningDe: 'Fahrkarte', pos: PartOfSpeech.nomen, domain: VocabDomain.verkehr),
  PoolEntry(id: 'lex_ja_hoomu', kana: 'ホーム', meaningDe: 'Bahnsteig', pos: PartOfSpeech.nomen, domain: VocabDomain.verkehr),
  PoolEntry(id: 'lex_ja_ryokou', kana: 'りょこう', written: '旅行', meaningDe: 'Reise', pos: PartOfSpeech.nomen, domain: VocabDomain.verkehr),
  PoolEntry(id: 'lex_ja_nimotsu', kana: 'にもつ', written: '荷物', meaningDe: 'Gepäck', pos: PartOfSpeech.nomen, domain: VocabDomain.verkehr),
  PoolEntry(id: 'lex_ja_chizu', kana: 'ちず', written: '地図', meaningDe: 'Landkarte', pos: PartOfSpeech.nomen, domain: VocabDomain.verkehr),
  PoolEntry(id: 'lex_ja_tenki', kana: 'てんき', written: '天気', meaningDe: 'Wetter', pos: PartOfSpeech.nomen, domain: VocabDomain.wetter),
  PoolEntry(id: 'lex_ja_ame', kana: 'あめ', written: '雨', meaningDe: 'Regen', pos: PartOfSpeech.nomen, domain: VocabDomain.wetter, plannedEpisode: 1, status: PoolStatus.ausgeliefert),
  PoolEntry(id: 'lex_ja_yuki', kana: 'ゆき', written: '雪', meaningDe: 'Schnee', pos: PartOfSpeech.nomen, domain: VocabDomain.wetter),
  PoolEntry(id: 'lex_ja_kaze_wind', kana: 'かぜ', written: '風', meaningDe: 'Wind', pos: PartOfSpeech.nomen, domain: VocabDomain.wetter),
  PoolEntry(id: 'lex_ja_kumo', kana: 'くも', written: '雲', meaningDe: 'Wolke', pos: PartOfSpeech.nomen, domain: VocabDomain.wetter),
  PoolEntry(id: 'lex_ja_sora', kana: 'そら', written: '空', meaningDe: 'Himmel', pos: PartOfSpeech.nomen, domain: VocabDomain.wetter),
  PoolEntry(id: 'lex_ja_hare', kana: 'はれ', written: '晴れ', meaningDe: 'heiteres Wetter', pos: PartOfSpeech.nomen, domain: VocabDomain.wetter),
  PoolEntry(id: 'lex_ja_kumori', kana: 'くもり', written: '曇り', meaningDe: 'bedecktes Wetter', pos: PartOfSpeech.nomen, domain: VocabDomain.wetter),
  PoolEntry(id: 'lex_ja_taifuu', kana: 'たいふう', written: '台風', meaningDe: 'Taifun', pos: PartOfSpeech.nomen, domain: VocabDomain.wetter),
  PoolEntry(id: 'lex_ja_samui', kana: 'さむい', written: '寒い', meaningDe: 'kalt (Wetter)', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.wetter, plannedEpisode: 1, status: PoolStatus.ausgeliefert),
  PoolEntry(id: 'lex_ja_atsui_weather', kana: 'あつい', written: '暑い', meaningDe: 'heiß (Wetter)', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.wetter),
  PoolEntry(id: 'lex_ja_suzushii', kana: 'すずしい', written: '涼しい', meaningDe: 'kühl', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.wetter),
  PoolEntry(id: 'lex_ja_atatakai', kana: 'あたたかい', written: '暖かい', meaningDe: 'warm', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.wetter),
  PoolEntry(id: 'lex_ja_yama', kana: 'やま', written: '山', meaningDe: 'Berg', pos: PartOfSpeech.nomen, domain: VocabDomain.natur),
  PoolEntry(id: 'lex_ja_kawa', kana: 'かわ', written: '川', meaningDe: 'Fluss', pos: PartOfSpeech.nomen, domain: VocabDomain.natur),
  PoolEntry(id: 'lex_ja_umi', kana: 'うみ', written: '海', meaningDe: 'Meer', pos: PartOfSpeech.nomen, domain: VocabDomain.natur),
  PoolEntry(id: 'lex_ja_ki', kana: 'き', written: '木', meaningDe: 'Baum', pos: PartOfSpeech.nomen, domain: VocabDomain.natur),
  PoolEntry(id: 'lex_ja_hana_flower', kana: 'はな', written: '花', meaningDe: 'Blume', pos: PartOfSpeech.nomen, domain: VocabDomain.natur),
  PoolEntry(id: 'lex_ja_ike', kana: 'いけ', written: '池', meaningDe: 'Teich', pos: PartOfSpeech.nomen, domain: VocabDomain.natur),
  PoolEntry(id: 'lex_ja_hi_fire', kana: 'ひ', written: '火', meaningDe: 'Feuer', pos: PartOfSpeech.nomen, domain: VocabDomain.natur),
  PoolEntry(id: 'lex_ja_dog', kana: 'いぬ', written: '犬', meaningDe: 'Hund', pos: PartOfSpeech.nomen, domain: VocabDomain.natur),
  PoolEntry(id: 'lex_ja_cat', kana: 'ねこ', written: '猫', meaningDe: 'Katze', pos: PartOfSpeech.nomen, domain: VocabDomain.natur),
  PoolEntry(id: 'lex_ja_tori', kana: 'とり', written: '鳥', meaningDe: 'Vogel', pos: PartOfSpeech.nomen, domain: VocabDomain.natur),
];
