//
// Wortvorrat 800, Liste A: Zahlen, Zähler, Uhrzeit, Kalender.
// Quelle: Plan docs/superpowers/plans/2026-09-18-wortvorrat-800.md, Task 3.

import 'pool_entry.dart';

const List<PoolEntry> vocabPoolJaZahlenZeit = [
  PoolEntry(id: 'lex_ja_ichi', kana: 'いち', written: '一', meaningDe: 'eins', pos: PartOfSpeech.zahl, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_ni', kana: 'に', written: '二', meaningDe: 'zwei', pos: PartOfSpeech.zahl, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_san', kana: 'さん', written: '三', meaningDe: 'drei', pos: PartOfSpeech.zahl, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_yon', kana: 'よん', written: '四', meaningDe: 'vier', pos: PartOfSpeech.zahl, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_go', kana: 'ご', written: '五', meaningDe: 'fünf', pos: PartOfSpeech.zahl, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_roku', kana: 'ろく', written: '六', meaningDe: 'sechs', pos: PartOfSpeech.zahl, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_nana', kana: 'なな', written: '七', meaningDe: 'sieben', pos: PartOfSpeech.zahl, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_hachi', kana: 'はち', written: '八', meaningDe: 'acht', pos: PartOfSpeech.zahl, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_kyuu', kana: 'きゅう', written: '九', meaningDe: 'neun', pos: PartOfSpeech.zahl, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_juu', kana: 'じゅう', written: '十', meaningDe: 'zehn', pos: PartOfSpeech.zahl, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_hyaku', kana: 'ひゃく', written: '百', meaningDe: 'hundert', pos: PartOfSpeech.zahl, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_sen', kana: 'せん', written: '千', meaningDe: 'tausend', pos: PartOfSpeech.zahl, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_man', kana: 'まん', written: '万', meaningDe: 'zehntausend', pos: PartOfSpeech.zahl, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_zero', kana: 'ゼロ', meaningDe: 'null', pos: PartOfSpeech.zahl, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_han', kana: 'はん', written: '半', meaningDe: 'halb', pos: PartOfSpeech.zahl, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_bangou', kana: 'ばんごう', written: '番号', meaningDe: 'Nummer', pos: PartOfSpeech.nomen, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_kazu', kana: 'かず', written: '数', meaningDe: 'Zahl, Anzahl', pos: PartOfSpeech.nomen, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_hitotsu', kana: 'ひとつ', written: '一つ', meaningDe: 'eins (Stück)', pos: PartOfSpeech.zaehlwort, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_futatsu', kana: 'ふたつ', written: '二つ', meaningDe: 'zwei (Stück)', pos: PartOfSpeech.zaehlwort, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_mittsu', kana: 'みっつ', written: '三つ', meaningDe: 'drei (Stück)', pos: PartOfSpeech.zaehlwort, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_yottsu', kana: 'よっつ', written: '四つ', meaningDe: 'vier (Stück)', pos: PartOfSpeech.zaehlwort, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_itsutsu', kana: 'いつつ', written: '五つ', meaningDe: 'fünf (Stück)', pos: PartOfSpeech.zaehlwort, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_muttsu', kana: 'むっつ', written: '六つ', meaningDe: 'sechs (Stück)', pos: PartOfSpeech.zaehlwort, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_nanatsu', kana: 'ななつ', written: '七つ', meaningDe: 'sieben (Stück)', pos: PartOfSpeech.zaehlwort, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_yattsu', kana: 'やっつ', written: '八つ', meaningDe: 'acht (Stück)', pos: PartOfSpeech.zaehlwort, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_kokonotsu', kana: 'ここのつ', written: '九つ', meaningDe: 'neun (Stück)', pos: PartOfSpeech.zaehlwort, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_too', kana: 'とお', written: '十', meaningDe: 'zehn (Stück)', pos: PartOfSpeech.zaehlwort, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_ikutsu', kana: 'いくつ', meaningDe: 'wie viele', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_hitori', kana: 'ひとり', written: '一人', meaningDe: 'allein, eine Person', pos: PartOfSpeech.zaehlwort, domain: VocabDomain.zahlen, plannedEpisode: 1, status: PoolStatus.ausgeliefert),
  PoolEntry(id: 'lex_ja_futari', kana: 'ふたり', written: '二人', meaningDe: 'zwei Personen', pos: PartOfSpeech.zaehlwort, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_sannin', kana: 'さんにん', written: '三人', meaningDe: 'drei Personen', pos: PartOfSpeech.zaehlwort, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_nannin', kana: 'なんにん', written: '何人', meaningDe: 'wie viele Personen', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_en', kana: 'えん', written: '円', meaningDe: 'Yen', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_kai', kana: 'かい', written: '回', meaningDe: 'Mal', pos: PartOfSpeech.zaehlwort, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_mai', kana: 'まい', written: '枚', meaningDe: 'Blatt, Stück (flach)', pos: PartOfSpeech.zaehlwort, domain: VocabDomain.zahlen),
  PoolEntry(id: 'lex_ja_jikan', kana: 'じかん', written: '時間', meaningDe: 'Zeit, Stunde', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_ji', kana: 'じ', written: '時', meaningDe: 'Uhr (Stunde)', pos: PartOfSpeech.zaehlwort, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_fun', kana: 'ふん', written: '分', meaningDe: 'Minute', pos: PartOfSpeech.zaehlwort, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_ima', kana: 'いま', written: '今', meaningDe: 'jetzt', pos: PartOfSpeech.adverb, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_nanji', kana: 'なんじ', written: '何時', meaningDe: 'wie spät', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_asa', kana: 'あさ', written: '朝', meaningDe: 'Morgen', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_hiru', kana: 'ひる', written: '昼', meaningDe: 'Mittag', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_ban', kana: 'ばん', written: '晩', meaningDe: 'Abend', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_yoru', kana: 'よる', written: '夜', meaningDe: 'Nacht', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_yuugata', kana: 'ゆうがた', written: '夕方', meaningDe: 'früher Abend', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_gozen', kana: 'ごぜん', written: '午前', meaningDe: 'Vormittag', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_gogo', kana: 'ごご', written: '午後', meaningDe: 'Nachmittag', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_kyou', kana: 'きょう', written: '今日', meaningDe: 'heute', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_ashita', kana: 'あした', written: '明日', meaningDe: 'morgen', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_kinou', kana: 'きのう', written: '昨日', meaningDe: 'gestern', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_asatte', kana: 'あさって', meaningDe: 'übermorgen', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_ototoi', kana: 'おととい', meaningDe: 'vorgestern', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_mainichi', kana: 'まいにち', written: '毎日', meaningDe: 'jeden Tag', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_maiasa', kana: 'まいあさ', written: '毎朝', meaningDe: 'jeden Morgen', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_maiban', kana: 'まいばん', written: '毎晩', meaningDe: 'jeden Abend', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_maishuu', kana: 'まいしゅう', written: '毎週', meaningDe: 'jede Woche', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_konshuu', kana: 'こんしゅう', written: '今週', meaningDe: 'diese Woche', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_raishuu', kana: 'らいしゅう', written: '来週', meaningDe: 'nächste Woche', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_senshuu', kana: 'せんしゅう', written: '先週', meaningDe: 'letzte Woche', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_kongetsu', kana: 'こんげつ', written: '今月', meaningDe: 'dieser Monat', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_raigetsu', kana: 'らいげつ', written: '来月', meaningDe: 'nächster Monat', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_sengetsu', kana: 'せんげつ', written: '先月', meaningDe: 'letzter Monat', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_kotoshi', kana: 'ことし', written: '今年', meaningDe: 'dieses Jahr', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_rainen', kana: 'らいねん', written: '来年', meaningDe: 'nächstes Jahr', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_kyonen', kana: 'きょねん', written: '去年', meaningDe: 'letztes Jahr', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_shuu', kana: 'しゅう', written: '週', meaningDe: 'Woche', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_tsuki', kana: 'つき', written: '月', meaningDe: 'Monat, Mond', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_nen', kana: 'ねん', written: '年', meaningDe: 'Jahr', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_hi_day', kana: 'ひ', written: '日', meaningDe: 'Tag', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_ichinichi', kana: 'いちにち', written: '一日', meaningDe: 'ein Tag (Dauer)', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_toki', kana: 'とき', written: '時', meaningDe: 'Zeit, Zeitpunkt', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_ato', kana: 'あと', written: '後', meaningDe: 'später, danach', pos: PartOfSpeech.adverb, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_getsuyoubi', kana: 'げつようび', written: '月曜日', meaningDe: 'Montag', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_kayoubi', kana: 'かようび', written: '火曜日', meaningDe: 'Dienstag', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_suiyoubi', kana: 'すいようび', written: '水曜日', meaningDe: 'Mittwoch', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_mokuyoubi', kana: 'もくようび', written: '木曜日', meaningDe: 'Donnerstag', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_kinyoubi', kana: 'きんようび', written: '金曜日', meaningDe: 'Freitag', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_doyoubi', kana: 'どようび', written: '土曜日', meaningDe: 'Samstag', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_nichiyoubi', kana: 'にちようび', written: '日曜日', meaningDe: 'Sonntag', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_nanyoubi', kana: 'なんようび', written: '何曜日', meaningDe: 'welcher Wochentag', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_ichigatsu', kana: 'いちがつ', written: '一月', meaningDe: 'Januar', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_nigatsu', kana: 'にがつ', written: '二月', meaningDe: 'Februar', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_sangatsu', kana: 'さんがつ', written: '三月', meaningDe: 'März', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_shigatsu', kana: 'しがつ', written: '四月', meaningDe: 'April', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_gogatsu', kana: 'ごがつ', written: '五月', meaningDe: 'Mai', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_rokugatsu', kana: 'ろくがつ', written: '六月', meaningDe: 'Juni', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_shichigatsu', kana: 'しちがつ', written: '七月', meaningDe: 'Juli', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_hachigatsu', kana: 'はちがつ', written: '八月', meaningDe: 'August', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_kugatsu', kana: 'くがつ', written: '九月', meaningDe: 'September', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_juugatsu', kana: 'じゅうがつ', written: '十月', meaningDe: 'Oktober', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_juuichigatsu', kana: 'じゅういちがつ', written: '十一月', meaningDe: 'November', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_juunigatsu', kana: 'じゅうにがつ', written: '十二月', meaningDe: 'Dezember', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_nangatsu', kana: 'なんがつ', written: '何月', meaningDe: 'welcher Monat', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_tsuitachi', kana: 'ついたち', written: '一日', meaningDe: 'der Erste', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_futsuka', kana: 'ふつか', written: '二日', meaningDe: 'der Zweite', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_mikka', kana: 'みっか', written: '三日', meaningDe: 'der Dritte', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_yokka', kana: 'よっか', written: '四日', meaningDe: 'der Vierte', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_itsuka_date', kana: 'いつか', written: '五日', meaningDe: 'der Fünfte', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_muika', kana: 'むいか', written: '六日', meaningDe: 'der Sechste', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_nanoka', kana: 'なのか', written: '七日', meaningDe: 'der Siebte', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_youka', kana: 'ようか', written: '八日', meaningDe: 'der Achte', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_kokonoka', kana: 'ここのか', written: '九日', meaningDe: 'der Neunte', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_tooka', kana: 'とおか', written: '十日', meaningDe: 'der Zehnte', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_hatsuka', kana: 'はつか', written: '二十日', meaningDe: 'der Zwanzigste', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_nannichi', kana: 'なんにち', written: '何日', meaningDe: 'welcher Tag', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_haru', kana: 'はる', written: '春', meaningDe: 'Frühling', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_natsu', kana: 'なつ', written: '夏', meaningDe: 'Sommer', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_aki', kana: 'あき', written: '秋', meaningDe: 'Herbst', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_fuyu', kana: 'ふゆ', written: '冬', meaningDe: 'Winter', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_tanjoubi', kana: 'たんじょうび', written: '誕生日', meaningDe: 'Geburtstag', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
  PoolEntry(id: 'lex_ja_yasumi', kana: 'やすみ', written: '休み', meaningDe: 'Ruhetag, frei', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit),
];
