//
// Wortvorrat 800, Liste G: Werkstatt, Post, Schule, Sprache, Dinge, Farben, Erinnerung; Reservebank.
// Quelle: Plan docs/superpowers/plans/2026-09-18-wortvorrat-800.md, Task 9.

import 'pool_entry.dart';

const List<PoolEntry> vocabPoolJaAlltag = [
  PoolEntry(id: 'lex_ja_hari', kana: 'はり', written: '針', meaningDe: 'Nadel', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_ito', kana: 'いと', written: '糸', meaningDe: 'Faden', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_hasami', kana: 'はさみ', meaningDe: 'Schere', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_botan', kana: 'ボタン', meaningDe: 'Knopf', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_hone', kana: 'ほね', written: '骨', meaningDe: 'Knochen, Strebe (Schirm)', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_nuno', kana: 'ぬの', written: '布', meaningDe: 'Stoff', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_teepu', kana: 'テープ', meaningDe: 'Klebeband', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_himo', kana: 'ひも', meaningDe: 'Schnur', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_dougu', kana: 'どうぐ', written: '道具', meaningDe: 'Werkzeug', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_kikai', kana: 'きかい', written: '機械', meaningDe: 'Maschine', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_denki', kana: 'でんき', written: '電気', meaningDe: 'Strom, Licht', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_kagi', kana: 'かぎ', written: '鍵', meaningDe: 'Schlüssel', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_shattaa', kana: 'シャッター', meaningDe: 'Rollladen', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_hako', kana: 'はこ', written: '箱', meaningDe: 'Kiste', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_gomi', kana: 'ごみ', meaningDe: 'Müll', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_shigoto', kana: 'しごと', written: '仕事', meaningDe: 'Arbeit', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_shuuri', kana: 'しゅうり', written: '修理', meaningDe: 'Reparatur', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_abura', kana: 'あぶら', written: '油', meaningDe: 'Öl', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_neji', kana: 'ネジ', meaningDe: 'Schraube', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_kugi', kana: 'くぎ', written: '釘', meaningDe: 'Nagel (Werkstatt)', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_ita', kana: 'いた', written: '板', meaningDe: 'Brett', pos: PartOfSpeech.nomen, domain: VocabDomain.werkstatt),
  PoolEntry(id: 'lex_ja_tegami', kana: 'てがみ', written: '手紙', meaningDe: 'Brief', pos: PartOfSpeech.nomen, domain: VocabDomain.post),
  PoolEntry(id: 'lex_ja_hagaki', kana: 'はがき', meaningDe: 'Postkarte', pos: PartOfSpeech.nomen, domain: VocabDomain.post),
  PoolEntry(id: 'lex_ja_kitte', kana: 'きって', written: '切手', meaningDe: 'Briefmarke', pos: PartOfSpeech.nomen, domain: VocabDomain.post),
  PoolEntry(id: 'lex_ja_fuutou', kana: 'ふうとう', written: '封筒', meaningDe: 'Umschlag', pos: PartOfSpeech.nomen, domain: VocabDomain.post),
  PoolEntry(id: 'lex_ja_kozutsumi', kana: 'こづつみ', written: '小包', meaningDe: 'Paket', pos: PartOfSpeech.nomen, domain: VocabDomain.post),
  PoolEntry(id: 'lex_ja_yuubin', kana: 'ゆうびん', written: '郵便', meaningDe: 'Post', pos: PartOfSpeech.nomen, domain: VocabDomain.post),
  PoolEntry(id: 'lex_ja_denwa', kana: 'でんわ', written: '電話', meaningDe: 'Telefon', pos: PartOfSpeech.nomen, domain: VocabDomain.post),
  PoolEntry(id: 'lex_ja_denwabangou', kana: 'でんわばんごう', written: '電話番号', meaningDe: 'Telefonnummer', pos: PartOfSpeech.nomen, domain: VocabDomain.post),
  PoolEntry(id: 'lex_ja_terehonkaado', kana: 'テレホンカード', meaningDe: 'Telefonkarte', pos: PartOfSpeech.nomen, domain: VocabDomain.post),
  PoolEntry(id: 'lex_ja_koushuudenwa', kana: 'こうしゅうでんわ', written: '公衆電話', meaningDe: 'öffentliches Telefon', pos: PartOfSpeech.nomen, domain: VocabDomain.post),
  PoolEntry(id: 'lex_ja_fakkusu', kana: 'ファックス', meaningDe: 'Fax', pos: PartOfSpeech.nomen, domain: VocabDomain.post),
  PoolEntry(id: 'lex_ja_juusho', kana: 'じゅうしょ', written: '住所', meaningDe: 'Adresse', pos: PartOfSpeech.nomen, domain: VocabDomain.post),
  PoolEntry(id: 'lex_ja_posuto', kana: 'ポスト', meaningDe: 'Briefkasten', pos: PartOfSpeech.nomen, domain: VocabDomain.post),
  PoolEntry(id: 'lex_ja_shinbun', kana: 'しんぶん', written: '新聞', meaningDe: 'Zeitung', pos: PartOfSpeech.nomen, domain: VocabDomain.post),
  PoolEntry(id: 'lex_ja_zasshi', kana: 'ざっし', written: '雑誌', meaningDe: 'Zeitschrift', pos: PartOfSpeech.nomen, domain: VocabDomain.post),
  PoolEntry(id: 'lex_ja_terebi', kana: 'テレビ', meaningDe: 'Fernseher', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_rajio', kana: 'ラジオ', meaningDe: 'Radio', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_nyuusu', kana: 'ニュース', meaningDe: 'Nachrichten', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_kamera', kana: 'カメラ', meaningDe: 'Kamera', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_shashin', kana: 'しゃしん', written: '写真', meaningDe: 'Foto', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_firumu', kana: 'フィルム', meaningDe: 'Film (Kamera)', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_bideo', kana: 'ビデオ', meaningDe: 'Video', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_kasetto', kana: 'カセット', meaningDe: 'Kassette', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_rekoodo', kana: 'レコード', meaningDe: 'Schallplatte', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_eiga', kana: 'えいが', written: '映画', meaningDe: 'Film (Kino)', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_ongaku', kana: 'おんがく', written: '音楽', meaningDe: 'Musik', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_uta', kana: 'うた', written: '歌', meaningDe: 'Lied', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_chirashi', kana: 'チラシ', meaningDe: 'Flugblatt', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_kanban', kana: 'かんばん', written: '看板', meaningDe: 'Schild', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_kyoushitsu', kana: 'きょうしつ', written: '教室', meaningDe: 'Klassenzimmer', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_jugyou', kana: 'じゅぎょう', written: '授業', meaningDe: 'Unterricht', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_shukudai', kana: 'しゅくだい', written: '宿題', meaningDe: 'Hausaufgabe', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_tesuto', kana: 'テスト', meaningDe: 'Test', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_nooto', kana: 'ノート', meaningDe: 'Heft', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_enpitsu', kana: 'えんぴつ', written: '鉛筆', meaningDe: 'Bleistift', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_pen', kana: 'ペン', meaningDe: 'Stift', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_keshigomu', kana: 'けしゴム', written: '消しゴム', meaningDe: 'Radiergummi', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_tsukue', kana: 'つくえ', written: '机', meaningDe: 'Schreibtisch', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_isu', kana: 'いす', meaningDe: 'Stuhl', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_hon', kana: 'ほん', written: '本', meaningDe: 'Buch', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_jisho', kana: 'じしょ', written: '辞書', meaningDe: 'Wörterbuch', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_kokuban', kana: 'こくばん', written: '黒板', meaningDe: 'Tafel', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_kurasu', kana: 'クラス', meaningDe: 'Klasse', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_watashitachi', kana: 'わたしたち', written: '私たち', meaningDe: 'wir', pos: PartOfSpeech.pronomen, domain: VocabDomain.menschen),
  PoolEntry(id: 'lex_ja_renshuu', kana: 'れんしゅう', written: '練習', meaningDe: 'Übung', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_benkyou', kana: 'べんきょう', written: '勉強', meaningDe: 'das Lernen', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_mondai', kana: 'もんだい', written: '問題', meaningDe: 'Problem, Aufgabe', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_kotae', kana: 'こたえ', written: '答え', meaningDe: 'Antwort', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_shitsumon', kana: 'しつもん', written: '質問', meaningDe: 'Frage', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_peeji', kana: 'ページ', meaningDe: 'Seite (Buch)', pos: PartOfSpeech.nomen, domain: VocabDomain.schule),
  PoolEntry(id: 'lex_ja_chuumon', kana: 'ちゅうもん', written: '注文', meaningDe: 'Bestellung', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_kotoba', kana: 'ことば', written: '言葉', meaningDe: 'Wort', pos: PartOfSpeech.nomen, domain: VocabDomain.sprache),
  PoolEntry(id: 'lex_ja_nihongo', kana: 'にほんご', written: '日本語', meaningDe: 'Japanisch', pos: PartOfSpeech.nomen, domain: VocabDomain.sprache),
  PoolEntry(id: 'lex_ja_doitsugo', kana: 'ドイツご', written: 'ドイツ語', meaningDe: 'Deutsch', pos: PartOfSpeech.nomen, domain: VocabDomain.sprache),
  PoolEntry(id: 'lex_ja_eigo', kana: 'えいご', written: '英語', meaningDe: 'Englisch', pos: PartOfSpeech.nomen, domain: VocabDomain.sprache),
  PoolEntry(id: 'lex_ja_kanji', kana: 'かんじ', written: '漢字', meaningDe: 'Kanji', pos: PartOfSpeech.nomen, domain: VocabDomain.sprache),
  PoolEntry(id: 'lex_ja_hiragana', kana: 'ひらがな', meaningDe: 'Hiragana', pos: PartOfSpeech.nomen, domain: VocabDomain.sprache),
  PoolEntry(id: 'lex_ja_katakana', kana: 'カタカナ', meaningDe: 'Katakana', pos: PartOfSpeech.nomen, domain: VocabDomain.sprache),
  PoolEntry(id: 'lex_ja_imi', kana: 'いみ', written: '意味', meaningDe: 'Bedeutung', pos: PartOfSpeech.nomen, domain: VocabDomain.sprache),
  PoolEntry(id: 'lex_ja_hanashi', kana: 'はなし', written: '話', meaningDe: 'Erzählung, Gespräch', pos: PartOfSpeech.nomen, domain: VocabDomain.sprache),
  PoolEntry(id: 'lex_ja_ji_character', kana: 'じ', written: '字', meaningDe: 'Schriftzeichen', pos: PartOfSpeech.nomen, domain: VocabDomain.sprache),
  PoolEntry(id: 'lex_ja_hatsuon', kana: 'はつおん', written: '発音', meaningDe: 'Aussprache', pos: PartOfSpeech.nomen, domain: VocabDomain.sprache),
  PoolEntry(id: 'lex_ja_kaiwa', kana: 'かいわ', written: '会話', meaningDe: 'Gespräch', pos: PartOfSpeech.nomen, domain: VocabDomain.sprache),
  PoolEntry(id: 'lex_ja_bun', kana: 'ぶん', written: '文', meaningDe: 'Satz', pos: PartOfSpeech.nomen, domain: VocabDomain.sprache),
  PoolEntry(id: 'lex_ja_mono', kana: 'もの', written: '物', meaningDe: 'Ding', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_kami_paper', kana: 'かみ', written: '紙', meaningDe: 'Papier', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_iro', kana: 'いろ', written: '色', meaningDe: 'Farbe', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_oto', kana: 'おと', written: '音', meaningDe: 'Geräusch', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_nioi', kana: 'におい', meaningDe: 'Geruch', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_hokori', kana: 'ほこり', meaningDe: 'Staub', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_ana', kana: 'あな', written: '穴', meaningDe: 'Loch', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_tana', kana: 'たな', written: '棚', meaningDe: 'Regal', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_beddo', kana: 'ベッド', meaningDe: 'Bett', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_futon', kana: 'ふとん', written: '布団', meaningDe: 'Futon', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_taoru', kana: 'タオル', meaningDe: 'Handtuch', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_sekken', kana: 'せっけん', meaningDe: 'Seife', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_hikari', kana: 'ひかり', written: '光', meaningDe: 'Licht (Schein)', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_kage', kana: 'かげ', written: '影', meaningDe: 'Schatten', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_kagami', kana: 'かがみ', written: '鏡', meaningDe: 'Spiegel', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_karendaa', kana: 'カレンダー', meaningDe: 'Kalender', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_omiyage', kana: 'おみやげ', written: 'お土産', meaningDe: 'Mitbringsel', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_purezento', kana: 'プレゼント', meaningDe: 'Geschenk', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_senpuuki', kana: 'せんぷうき', written: '扇風機', meaningDe: 'Ventilator', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_sutoobu', kana: 'ストーブ', meaningDe: 'Ofen, Heizung', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_reizouko', kana: 'れいぞうこ', written: '冷蔵庫', meaningDe: 'Kühlschrank', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_sentakuki', kana: 'せんたくき', written: '洗濯機', meaningDe: 'Waschmaschine', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_jidouhanbaiki', kana: 'じどうはんばいき', written: '自動販売機', meaningDe: 'Verkaufsautomat', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_gomibako', kana: 'ごみばこ', written: 'ごみ箱', meaningDe: 'Mülleimer', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_tebukuro', kana: 'てぶくろ', written: '手袋', meaningDe: 'Handschuhe', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_matchi', kana: 'マッチ', meaningDe: 'Streichholz', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_raitaa', kana: 'ライター', meaningDe: 'Feuerzeug', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_ishi', kana: 'いし', written: '石', meaningDe: 'Stein', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_tsuchi', kana: 'つち', written: '土', meaningDe: 'Erde', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_nabe', kana: 'なべ', meaningDe: 'Topf', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_e', kana: 'え', written: '絵', meaningDe: 'Bild, Zeichnung', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_denchi', kana: 'でんち', written: '電池', meaningDe: 'Batterie', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_katachi', kana: 'かたち', written: '形', meaningDe: 'Form', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_hikidashi', kana: 'ひきだし', written: '引き出し', meaningDe: 'Schublade', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_fuda', kana: 'ふだ', written: '札', meaningDe: 'Schildchen, Anhänger', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_memo', kana: 'メモ', meaningDe: 'Notizzettel', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_techou', kana: 'てちょう', written: '手帳', meaningDe: 'Notizbuch', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_hashira', kana: 'はしら', written: '柱', meaningDe: 'Pfosten', pos: PartOfSpeech.nomen, domain: VocabDomain.haus),
  PoolEntry(id: 'lex_ja_yane', kana: 'やね', written: '屋根', meaningDe: 'Dach', pos: PartOfSpeech.nomen, domain: VocabDomain.haus),
  PoolEntry(id: 'lex_ja_aka', kana: 'あか', written: '赤', meaningDe: 'Rot', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_ao', kana: 'あお', written: '青', meaningDe: 'Blau', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_kuro', kana: 'くろ', written: '黒', meaningDe: 'Schwarz', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_shiro', kana: 'しろ', written: '白', meaningDe: 'Weiß', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_kiiro', kana: 'きいろ', written: '黄色', meaningDe: 'Gelb', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_midori', kana: 'みどり', written: '緑', meaningDe: 'Grün', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_chairo', kana: 'ちゃいろ', written: '茶色', meaningDe: 'Braun', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_mukashi', kana: 'むかし', written: '昔', meaningDe: 'früher, damals', pos: PartOfSpeech.nomen, domain: VocabDomain.erinnerung),
  PoolEntry(id: 'lex_ja_omoide', kana: 'おもいで', written: '思い出', meaningDe: 'Erinnerung', pos: PartOfSpeech.nomen, domain: VocabDomain.erinnerung),
  PoolEntry(id: 'lex_ja_yume', kana: 'ゆめ', written: '夢', meaningDe: 'Traum', pos: PartOfSpeech.nomen, domain: VocabDomain.erinnerung),
  PoolEntry(id: 'lex_ja_koto', kana: 'こと', meaningDe: 'Sache, Angelegenheit', pos: PartOfSpeech.nomen, domain: VocabDomain.erinnerung),
  PoolEntry(id: 'lex_ja_himitsu', kana: 'ひみつ', written: '秘密', meaningDe: 'Geheimnis', pos: PartOfSpeech.nomen, domain: VocabDomain.erinnerung),
  PoolEntry(id: 'lex_ja_monogatari', kana: 'ものがたり', written: '物語', meaningDe: 'Geschichte (Erzählung)', pos: PartOfSpeech.nomen, domain: VocabDomain.erinnerung),
  PoolEntry(id: 'lex_ja_nikki', kana: 'にっき', written: '日記', meaningDe: 'Tagebuch', pos: PartOfSpeech.nomen, domain: VocabDomain.erinnerung),
];

const List<PoolEntry> vocabPoolJaBank = [
  PoolEntry(id: 'lex_ja_nekutai', kana: 'ネクタイ', meaningDe: 'Krawatte', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_waishatsu', kana: 'ワイシャツ', meaningDe: 'Anzughemd', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_yubiwa', kana: 'ゆびわ', written: '指輪', meaningDe: 'Ring', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_yukata', kana: 'ゆかた', written: '浴衣', meaningDe: 'Sommerkimono', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_kimono', kana: 'きもの', written: '着物', meaningDe: 'Kimono', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_boorupen', kana: 'ボールペン', meaningDe: 'Kugelschreiber', pos: PartOfSpeech.nomen, domain: VocabDomain.schule, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_manshon', kana: 'マンション', meaningDe: 'Wohnblock', pos: PartOfSpeech.nomen, domain: VocabDomain.haus, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_apaato', kana: 'アパート', meaningDe: 'Mietwohnung', pos: PartOfSpeech.nomen, domain: VocabDomain.haus, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_mezamashidokei', kana: 'めざましどけい', written: '目覚まし時計', meaningDe: 'Wecker', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_puuru', kana: 'プール', meaningDe: 'Schwimmbad', pos: PartOfSpeech.nomen, domain: VocabDomain.orte, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_doubutsuen', kana: 'どうぶつえん', written: '動物園', meaningDe: 'Zoo', pos: PartOfSpeech.nomen, domain: VocabDomain.orte, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_bijutsukan', kana: 'びじゅつかん', written: '美術館', meaningDe: 'Kunstmuseum', pos: PartOfSpeech.nomen, domain: VocabDomain.orte, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_taishikan', kana: 'たいしかん', written: '大使館', meaningDe: 'Botschaft', pos: PartOfSpeech.nomen, domain: VocabDomain.orte, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_kouban', kana: 'こうばん', written: '交番', meaningDe: 'Polizeihäuschen', pos: PartOfSpeech.nomen, domain: VocabDomain.orte, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_onsen', kana: 'おんせん', written: '温泉', meaningDe: 'heiße Quelle', pos: PartOfSpeech.nomen, domain: VocabDomain.orte, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_sakura', kana: 'さくら', written: '桜', meaningDe: 'Kirschblüte', pos: PartOfSpeech.nomen, domain: VocabDomain.natur, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_kisetsu', kana: 'きせつ', written: '季節', meaningDe: 'Jahreszeit', pos: PartOfSpeech.nomen, domain: VocabDomain.zeit, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_tsuyu', kana: 'つゆ', written: '梅雨', meaningDe: 'Regenzeit', pos: PartOfSpeech.nomen, domain: VocabDomain.wetter, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_tamanegi', kana: 'たまねぎ', written: '玉ねぎ', meaningDe: 'Zwiebel', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_jagaimo', kana: 'じゃがいも', meaningDe: 'Kartoffel', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_ninjin', kana: 'にんじん', meaningDe: 'Karotte', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_ichigo', kana: 'いちご', meaningDe: 'Erdbeere', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_budou', kana: 'ぶどう', meaningDe: 'Traube', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_momo', kana: 'もも', written: '桃', meaningDe: 'Pfirsich', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_chawan', kana: 'ちゃわん', written: '茶碗', meaningDe: 'Reisschale', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_haizara', kana: 'はいざら', written: '灰皿', meaningDe: 'Aschenbecher', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_konsaato', kana: 'コンサート', meaningDe: 'Konzert', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_supootsu', kana: 'スポーツ', meaningDe: 'Sport', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_sakkaa', kana: 'サッカー', meaningDe: 'Fußball', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_yakyuu', kana: 'やきゅう', written: '野球', meaningDe: 'Baseball', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_gitaa', kana: 'ギター', meaningDe: 'Gitarre', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_piano', kana: 'ピアノ', meaningDe: 'Klavier', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_seikatsu', kana: 'せいかつ', written: '生活', meaningDe: 'Alltag, Leben', pos: PartOfSpeech.nomen, domain: VocabDomain.erinnerung, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_shumi', kana: 'しゅみ', written: '趣味', meaningDe: 'Hobby', pos: PartOfSpeech.nomen, domain: VocabDomain.erinnerung, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_omatsuri', kana: 'おまつり', written: 'お祭り', meaningDe: 'Fest', pos: PartOfSpeech.nomen, domain: VocabDomain.erinnerung, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_hanabi', kana: 'はなび', written: '花火', meaningDe: 'Feuerwerk', pos: PartOfSpeech.nomen, domain: VocabDomain.erinnerung, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_tsume', kana: 'つめ', written: '爪', meaningDe: 'Fingernagel', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_hige', kana: 'ひげ', meaningDe: 'Bart', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_senaka', kana: 'せなか', written: '背中', meaningDe: 'Rücken', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper, status: PoolStatus.bank),
  PoolEntry(id: 'lex_ja_nodo', kana: 'のど', meaningDe: 'Kehle', pos: PartOfSpeech.nomen, domain: VocabDomain.koerper, status: PoolStatus.bank),
];
