//
// Wortvorrat 800, Liste F: Adjektive, Adverbien, Fragewörter, Pronomen, Ausdrücke.
// Quelle: Plan docs/superpowers/plans/2026-09-18-wortvorrat-800.md, Task 8.

import 'pool_entry.dart';

const List<PoolEntry> vocabPoolJaAdjektiveAusdruecke = [
  PoolEntry(id: 'lex_ja_ookii', kana: 'おおきい', written: '大きい', meaningDe: 'groß', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_chiisai', kana: 'ちいさい', written: '小さい', meaningDe: 'klein', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_atarashii', kana: 'あたらしい', written: '新しい', meaningDe: 'neu', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_furui', kana: 'ふるい', written: '古い', meaningDe: 'alt (Sache)', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_ii', kana: 'いい', meaningDe: 'gut', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_warui', kana: 'わるい', written: '悪い', meaningDe: 'schlecht', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_takai', kana: 'たかい', written: '高い', meaningDe: 'hoch, teuer', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_hikui', kana: 'ひくい', written: '低い', meaningDe: 'niedrig', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_yasui', kana: 'やすい', written: '安い', meaningDe: 'billig', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_nagai', kana: 'ながい', written: '長い', meaningDe: 'lang', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_mijikai', kana: 'みじかい', written: '短い', meaningDe: 'kurz', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_hayai_early', kana: 'はやい', written: '早い', meaningDe: 'früh', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_hayai_fast', kana: 'はやい', written: '速い', meaningDe: 'schnell', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_osoi', kana: 'おそい', written: '遅い', meaningDe: 'spät, langsam', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_ooi', kana: 'おおい', written: '多い', meaningDe: 'viele', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_sukunai', kana: 'すくない', written: '少ない', meaningDe: 'wenige', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_hiroi', kana: 'ひろい', written: '広い', meaningDe: 'weit, geräumig', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_semai', kana: 'せまい', written: '狭い', meaningDe: 'eng', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_omoi', kana: 'おもい', written: '重い', meaningDe: 'schwer (Gewicht)', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_karui', kana: 'かるい', written: '軽い', meaningDe: 'leicht (Gewicht)', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_tsuyoi', kana: 'つよい', written: '強い', meaningDe: 'stark', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_yowai', kana: 'よわい', written: '弱い', meaningDe: 'schwach', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_atsui_hot', kana: 'あつい', written: '熱い', meaningDe: 'heiß (Sache)', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_tsumetai', kana: 'つめたい', written: '冷たい', meaningDe: 'kalt (Sache)', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_akarui', kana: 'あかるい', written: '明るい', meaningDe: 'hell', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_kurai', kana: 'くらい', written: '暗い', meaningDe: 'dunkel', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_oishii', kana: 'おいしい', meaningDe: 'lecker', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_mazui', kana: 'まずい', meaningDe: 'nicht lecker', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_amai', kana: 'あまい', written: '甘い', meaningDe: 'süß', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_karai', kana: 'からい', written: '辛い', meaningDe: 'scharf', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_itai', kana: 'いたい', written: '痛い', meaningDe: 'schmerzhaft', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_tanoshii', kana: 'たのしい', written: '楽しい', meaningDe: 'schön, macht Spaß', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_ureshii', kana: 'うれしい', written: '嬉しい', meaningDe: 'froh', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_kanashii', kana: 'かなしい', written: '悲しい', meaningDe: 'traurig', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_sabishii', kana: 'さびしい', written: '寂しい', meaningDe: 'einsam', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_kowai', kana: 'こわい', written: '怖い', meaningDe: 'unheimlich', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_omoshiroi', kana: 'おもしろい', written: '面白い', meaningDe: 'interessant', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_tsumaranai', kana: 'つまらない', meaningDe: 'langweilig', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_muzukashii', kana: 'むずかしい', written: '難しい', meaningDe: 'schwierig', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_yasashii_easy', kana: 'やさしい', written: '易しい', meaningDe: 'einfach', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_yasashii_kind', kana: 'やさしい', written: '優しい', meaningDe: 'freundlich', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_isogashii', kana: 'いそがしい', written: '忙しい', meaningDe: 'beschäftigt', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_abunai', kana: 'あぶない', written: '危ない', meaningDe: 'gefährlich', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_kitanai', kana: 'きたない', written: '汚い', meaningDe: 'schmutzig', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_kawaii', kana: 'かわいい', meaningDe: 'niedlich', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_wakai', kana: 'わかい', written: '若い', meaningDe: 'jung', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_tooi', kana: 'とおい', written: '遠い', meaningDe: 'weit weg', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_chikai', kana: 'ちかい', written: '近い', meaningDe: 'nah', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_marui', kana: 'まるい', written: '丸い', meaningDe: 'rund', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_shiroi', kana: 'しろい', written: '白い', meaningDe: 'weiß', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_kuroi', kana: 'くろい', written: '黒い', meaningDe: 'schwarz', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_akai', kana: 'あかい', written: '赤い', meaningDe: 'rot', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_aoi', kana: 'あおい', written: '青い', meaningDe: 'blau', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_kiiroi', kana: 'きいろい', written: '黄色い', meaningDe: 'gelb', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_hoshii', kana: 'ほしい', written: '欲しい', meaningDe: 'haben wollen', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_sugoi', kana: 'すごい', meaningDe: 'toll, gewaltig', pos: PartOfSpeech.iAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_kirei', kana: 'きれい', meaningDe: 'schön, sauber', pos: PartOfSpeech.naAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_shizuka', kana: 'しずか', written: '静か', meaningDe: 'ruhig', pos: PartOfSpeech.naAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_nigiyaka', kana: 'にぎやか', meaningDe: 'belebt', pos: PartOfSpeech.naAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_suki', kana: 'すき', written: '好き', meaningDe: 'mögen', pos: PartOfSpeech.naAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_kirai', kana: 'きらい', written: '嫌い', meaningDe: 'nicht mögen', pos: PartOfSpeech.naAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_jouzu', kana: 'じょうず', written: '上手', meaningDe: 'geschickt', pos: PartOfSpeech.naAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_heta', kana: 'へた', written: '下手', meaningDe: 'ungeschickt', pos: PartOfSpeech.naAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_yuumei', kana: 'ゆうめい', written: '有名', meaningDe: 'berühmt', pos: PartOfSpeech.naAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_shinsetsu', kana: 'しんせつ', written: '親切', meaningDe: 'hilfsbereit', pos: PartOfSpeech.naAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_benri', kana: 'べんり', written: '便利', meaningDe: 'praktisch', pos: PartOfSpeech.naAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_taihen', kana: 'たいへん', written: '大変', meaningDe: 'schlimm, anstrengend', pos: PartOfSpeech.naAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_hima', kana: 'ひま', written: '暇', meaningDe: 'frei (Zeit haben)', pos: PartOfSpeech.naAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_onaji', kana: 'おなじ', written: '同じ', meaningDe: 'gleich', pos: PartOfSpeech.naAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_iroiro', kana: 'いろいろ', meaningDe: 'verschiedene', pos: PartOfSpeech.naAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_taisetsu', kana: 'たいせつ', written: '大切', meaningDe: 'wichtig', pos: PartOfSpeech.naAdjektiv, domain: VocabDomain.adjektive),
  PoolEntry(id: 'lex_ja_dame', kana: 'だめ', meaningDe: 'geht nicht', pos: PartOfSpeech.naAdjektiv, domain: VocabDomain.ausdruecke, plannedEpisode: 1, status: PoolStatus.ausgeliefert),
  PoolEntry(id: 'lex_ja_daijoubu', kana: 'だいじょうぶ', written: '大丈夫', meaningDe: 'in Ordnung', pos: PartOfSpeech.naAdjektiv, domain: VocabDomain.ausdruecke, plannedEpisode: 1, status: PoolStatus.ausgeliefert),
  PoolEntry(id: 'lex_ja_totemo', kana: 'とても', meaningDe: 'sehr', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_sukoshi', kana: 'すこし', written: '少し', meaningDe: 'ein wenig', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_chotto', kana: 'ちょっと', meaningDe: 'ein bisschen', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_takusan', kana: 'たくさん', meaningDe: 'viel', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_motto', kana: 'もっと', meaningDe: 'mehr', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_zenzen', kana: 'ぜんぜん', written: '全然', meaningDe: 'überhaupt nicht', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_amari', kana: 'あまり', meaningDe: 'nicht sehr', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_itsumo', kana: 'いつも', meaningDe: 'immer', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_tokidoki', kana: 'ときどき', written: '時々', meaningDe: 'manchmal', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_yoku', kana: 'よく', meaningDe: 'oft, gut', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_mada', kana: 'まだ', meaningDe: 'noch', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_mou', kana: 'もう', meaningDe: 'schon', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_mata', kana: 'また', meaningDe: 'wieder', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_sugu', kana: 'すぐ', meaningDe: 'sofort', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_yukkuri', kana: 'ゆっくり', meaningDe: 'langsam', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_hayaku', kana: 'はやく', written: '早く', meaningDe: 'schnell, früh', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_isshoni', kana: 'いっしょに', written: '一緒に', meaningDe: 'zusammen', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_hitoride', kana: 'ひとりで', written: '一人で', meaningDe: 'allein (tun)', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_tabun', kana: 'たぶん', meaningDe: 'vielleicht', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_kitto', kana: 'きっと', meaningDe: 'bestimmt', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_mouichido', kana: 'もういちど', written: 'もう一度', meaningDe: 'noch einmal', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_hajimete', kana: 'はじめて', written: '初めて', meaningDe: 'zum ersten Mal', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_zenbu', kana: 'ぜんぶ', written: '全部', meaningDe: 'alles', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_massugu', kana: 'まっすぐ', meaningDe: 'geradeaus', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_taitei', kana: 'たいてい', meaningDe: 'meistens', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_ichiban', kana: 'いちばん', written: '一番', meaningDe: 'am meisten, Nummer eins', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_zutto', kana: 'ずっと', meaningDe: 'die ganze Zeit', pos: PartOfSpeech.adverb, domain: VocabDomain.adverbien),
  PoolEntry(id: 'lex_ja_what', kana: 'なに', written: '何', meaningDe: 'was', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_dare', kana: 'だれ', written: '誰', meaningDe: 'wer', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_itsu', kana: 'いつ', meaningDe: 'wann', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_doushite', kana: 'どうして', meaningDe: 'warum', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_naze', kana: 'なぜ', meaningDe: 'warum (förmlich)', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_dou', kana: 'どう', meaningDe: 'wie', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_donna', kana: 'どんな', meaningDe: 'was für ein', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_dono', kana: 'どの', meaningDe: 'welcher', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_dore', kana: 'どれ', meaningDe: 'welches', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_dochira', kana: 'どちら', meaningDe: 'welches (von zweien), wohin (höflich)', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_ikura', kana: 'いくら', meaningDe: 'wie viel (kostet)', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen, plannedEpisode: 1, status: PoolStatus.ausgeliefert),
  PoolEntry(id: 'lex_ja_kore', kana: 'これ', meaningDe: 'das hier', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen, plannedEpisode: 1, status: PoolStatus.ausgeliefert),
  PoolEntry(id: 'lex_ja_sore', kana: 'それ', meaningDe: 'das da', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_are', kana: 'あれ', meaningDe: 'das dort', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_kono', kana: 'この', meaningDe: 'dieser', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_sono', kana: 'その', meaningDe: 'der da', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_ano', kana: 'あの', meaningDe: 'jener', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_konna', kana: 'こんな', meaningDe: 'so ein', pos: PartOfSpeech.pronomen, domain: VocabDomain.fragen),
  PoolEntry(id: 'lex_ja_soshite', kana: 'そして', meaningDe: 'und dann', pos: PartOfSpeech.konjunktion, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_sorekara', kana: 'それから', meaningDe: 'danach', pos: PartOfSpeech.konjunktion, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_demo', kana: 'でも', meaningDe: 'aber', pos: PartOfSpeech.konjunktion, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_dakara', kana: 'だから', meaningDe: 'deshalb', pos: PartOfSpeech.konjunktion, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_shikashi', kana: 'しかし', meaningDe: 'jedoch', pos: PartOfSpeech.konjunktion, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_hai', kana: 'はい', meaningDe: 'ja', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke, plannedEpisode: 1, status: PoolStatus.ausgeliefert),
  PoolEntry(id: 'lex_ja_iie', kana: 'いいえ', meaningDe: 'nein', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke, plannedEpisode: 1, status: PoolStatus.ausgeliefert),
  PoolEntry(id: 'lex_ja_ee', kana: 'ええ', meaningDe: 'ja (weich)', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_un', kana: 'うん', meaningDe: 'ja (vertraut)', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_uun', kana: 'ううん', meaningDe: 'nein (vertraut)', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_sumimasen', kana: 'すみません', meaningDe: 'Entschuldigung', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke, plannedEpisode: 1, status: PoolStatus.ausgeliefert),
  PoolEntry(id: 'lex_ja_arigatou', kana: 'ありがとう', meaningDe: 'danke', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke, plannedEpisode: 1, status: PoolStatus.ausgeliefert),
  PoolEntry(id: 'lex_ja_douzo', kana: 'どうぞ', meaningDe: 'bitte (hier)', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke, plannedEpisode: 1, status: PoolStatus.ausgeliefert),
  PoolEntry(id: 'lex_ja_hontou', kana: 'ほんとう', written: '本当', meaningDe: 'wirklich', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke, plannedEpisode: 1, status: PoolStatus.ausgeliefert),
  PoolEntry(id: 'lex_ja_doumo', kana: 'どうも', meaningDe: 'danke, sehr', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_ohayou', kana: 'おはよう', meaningDe: 'guten Morgen', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_konnichiwa', kana: 'こんにちは', meaningDe: 'guten Tag', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_konbanwa', kana: 'こんばんは', meaningDe: 'guten Abend', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_oyasumi', kana: 'おやすみ', meaningDe: 'gute Nacht', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_sayounara', kana: 'さようなら', meaningDe: 'auf Wiedersehen', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_jaa', kana: 'じゃあ', meaningDe: 'also dann', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_matane', kana: 'またね', meaningDe: 'bis dann', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_onegaishimasu', kana: 'おねがいします', written: 'お願いします', meaningDe: 'bitte (ich bitte darum)', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_kudasai', kana: 'ください', meaningDe: 'bitte (geben Sie)', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_itadakimasu', kana: 'いただきます', meaningDe: 'guten Appetit', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_gochisousama', kana: 'ごちそうさま', meaningDe: 'danke fürs Essen', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_gomen', kana: 'ごめん', meaningDe: 'Entschuldigung (vertraut)', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_moshimoshi', kana: 'もしもし', meaningDe: 'hallo (am Telefon)', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_irasshaimase', kana: 'いらっしゃいませ', meaningDe: 'willkommen (im Laden)', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_tadaima', kana: 'ただいま', meaningDe: 'bin wieder da', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_okaeri', kana: 'おかえり', meaningDe: 'willkommen zurück', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_ittekimasu', kana: 'いってきます', meaningDe: 'bis später (beim Gehen)', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_itterasshai', kana: 'いってらっしゃい', meaningDe: 'komm gut zurück', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_omedetou', kana: 'おめでとう', meaningDe: 'Glückwunsch', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_kiwotsukete', kana: 'きをつけて', written: '気をつけて', meaningDe: 'pass auf', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_sou', kana: 'そう', meaningDe: 'so, genau', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_soudesune', kana: 'そうですね', meaningDe: 'ja, stimmt', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_shitsureishimasu', kana: 'しつれいします', written: '失礼します', meaningDe: 'entschuldigen Sie', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_otsukaresama', kana: 'おつかれさま', written: 'お疲れさま', meaningDe: 'danke für die Mühe', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_hajimemashite', kana: 'はじめまして', meaningDe: 'freut mich', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_douitashimashite', kana: 'どういたしまして', meaningDe: 'gern geschehen', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_youkoso', kana: 'ようこそ', meaningDe: 'willkommen', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_onakagasuita', kana: 'おなかがすいた', written: 'お腹がすいた', meaningDe: 'ich habe Hunger', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
  PoolEntry(id: 'lex_ja_nodogakawaita', kana: 'のどがかわいた', meaningDe: 'ich habe Durst', pos: PartOfSpeech.ausdruck, domain: VocabDomain.ausdruecke),
];
