//
// Wortvorrat 800, Liste E: Verben des Alltags.
// Quelle: Plan docs/superpowers/plans/2026-09-18-wortvorrat-800.md, Task 7.

import 'pool_entry.dart';

const List<PoolEntry> vocabPoolJaVerben = [
  PoolEntry(id: 'lex_ja_iku', kana: 'いく', written: '行く', meaningDe: 'gehen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kuru', kana: 'くる', written: '来る', meaningDe: 'kommen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kaeru_return', kana: 'かえる', written: '帰る', meaningDe: 'zurückkehren', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_aruku', kana: 'あるく', written: '歩く', meaningDe: 'zu Fuß gehen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_hashiru', kana: 'はしる', written: '走る', meaningDe: 'laufen, rennen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_tomaru', kana: 'とまる', written: '止まる', meaningDe: 'anhalten', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_tomeru', kana: 'とめる', written: '止める', meaningDe: 'anhalten (etwas)', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_magaru', kana: 'まがる', written: '曲がる', meaningDe: 'abbiegen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_wataru', kana: 'わたる', written: '渡る', meaningDe: 'überqueren', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_noru', kana: 'のる', written: '乗る', meaningDe: 'einsteigen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_oriru', kana: 'おりる', written: '降りる', meaningDe: 'aussteigen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_tsuku_arrive', kana: 'つく', written: '着く', meaningDe: 'ankommen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_dekakeru', kana: 'でかける', written: '出かける', meaningDe: 'ausgehen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_hairu', kana: 'はいる', written: '入る', meaningDe: 'hineingehen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_deru', kana: 'でる', written: '出る', meaningDe: 'hinausgehen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_akeru', kana: 'あける', written: '開ける', meaningDe: 'öffnen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_shimeru', kana: 'しめる', written: '閉める', meaningDe: 'schließen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_aku', kana: 'あく', written: '開く', meaningDe: 'sich öffnen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_shimaru', kana: 'しまる', written: '閉まる', meaningDe: 'sich schließen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_suwaru', kana: 'すわる', written: '座る', meaningDe: 'sich setzen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_tatsu', kana: 'たつ', written: '立つ', meaningDe: 'stehen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_neru', kana: 'ねる', written: '寝る', meaningDe: 'schlafen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_okiru', kana: 'おきる', written: '起きる', meaningDe: 'aufstehen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_eat', kana: 'たべる', written: '食べる', meaningDe: 'essen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_nomu', kana: 'のむ', written: '飲む', meaningDe: 'trinken', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_tsukuru', kana: 'つくる', written: '作る', meaningDe: 'machen, herstellen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kau', kana: 'かう', written: '買う', meaningDe: 'kaufen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_uru', kana: 'うる', written: '売る', meaningDe: 'verkaufen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_harau', kana: 'はらう', written: '払う', meaningDe: 'bezahlen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_morau', kana: 'もらう', meaningDe: 'bekommen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_ageru', kana: 'あげる', meaningDe: 'geben', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kureru', kana: 'くれる', meaningDe: 'mir geben', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kasu', kana: 'かす', written: '貸す', meaningDe: 'verleihen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kariru', kana: 'かりる', written: '借りる', meaningDe: 'ausleihen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kaesu', kana: 'かえす', written: '返す', meaningDe: 'zurückgeben', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_okuru', kana: 'おくる', written: '送る', meaningDe: 'schicken', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_todoku', kana: 'とどく', written: '届く', meaningDe: 'ankommen (Post)', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_dasu', kana: 'だす', written: '出す', meaningDe: 'herausholen, abschicken', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_ireru', kana: 'いれる', written: '入れる', meaningDe: 'hineintun', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_oku', kana: 'おく', written: '置く', meaningDe: 'hinstellen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_toru', kana: 'とる', written: '取る', meaningDe: 'nehmen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_motsu', kana: 'もつ', written: '持つ', meaningDe: 'halten, haben', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_motteiku', kana: 'もっていく', written: '持っていく', meaningDe: 'mitnehmen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_mottekuru', kana: 'もってくる', written: '持ってくる', meaningDe: 'mitbringen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_tsukau', kana: 'つかう', written: '使う', meaningDe: 'benutzen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_naosu', kana: 'なおす', written: '直す', meaningDe: 'reparieren', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kowareta', kana: 'こわれた', written: '壊れた', meaningDe: 'kaputt (gegangen)', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag, plannedEpisode: 1, status: PoolStatus.ausgeliefert),
  PoolEntry(id: 'lex_ja_kowasu', kana: 'こわす', written: '壊す', meaningDe: 'kaputt machen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kiru_cut', kana: 'きる', written: '切る', meaningDe: 'schneiden', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kiru_wear', kana: 'きる', written: '着る', meaningDe: 'anziehen (Oberteil)', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_nugu', kana: 'ぬぐ', written: '脱ぐ', meaningDe: 'ausziehen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_haku', kana: 'はく', meaningDe: 'anziehen (Hose, Schuhe)', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kaburu', kana: 'かぶる', meaningDe: 'aufsetzen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_nuu', kana: 'ぬう', written: '縫う', meaningDe: 'nähen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_arau', kana: 'あらう', written: '洗う', meaningDe: 'waschen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_souji_suru', kana: 'そうじする', written: '掃除する', meaningDe: 'putzen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_sentaku_suru', kana: 'せんたくする', written: '洗濯する', meaningDe: 'Wäsche waschen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_ryouri_suru', kana: 'りょうりする', written: '料理する', meaningDe: 'kochen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_benkyou_suru', kana: 'べんきょうする', written: '勉強する', meaningDe: 'lernen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_hataraku', kana: 'はたらく', written: '働く', meaningDe: 'arbeiten', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_yasumu', kana: 'やすむ', written: '休む', meaningDe: 'sich ausruhen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_asobu', kana: 'あそぶ', written: '遊ぶ', meaningDe: 'spielen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_oyogu', kana: 'およぐ', written: '泳ぐ', meaningDe: 'schwimmen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_utau', kana: 'うたう', written: '歌う', meaningDe: 'singen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_hanasu', kana: 'はなす', written: '話す', meaningDe: 'sprechen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_iu', kana: 'いう', written: '言う', meaningDe: 'sagen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kiku', kana: 'きく', written: '聞く', meaningDe: 'hören, fragen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_yomu', kana: 'よむ', written: '読む', meaningDe: 'lesen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kaku', kana: 'かく', written: '書く', meaningDe: 'schreiben', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_miru', kana: 'みる', written: '見る', meaningDe: 'sehen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_miseru', kana: 'みせる', written: '見せる', meaningDe: 'zeigen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_au', kana: 'あう', written: '会う', meaningDe: 'treffen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_matsu', kana: 'まつ', written: '待つ', meaningDe: 'warten', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_shiru', kana: 'しる', written: '知る', meaningDe: 'wissen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_wakaru', kana: 'わかる', written: '分かる', meaningDe: 'verstehen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_omou', kana: 'おもう', written: '思う', meaningDe: 'denken, meinen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_oboeru', kana: 'おぼえる', written: '覚える', meaningDe: 'sich merken', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_wasureru', kana: 'わすれる', written: '忘れる', meaningDe: 'vergessen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_oshieru', kana: 'おしえる', written: '教える', meaningDe: 'beibringen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_narau', kana: 'ならう', written: '習う', meaningDe: 'lernen (bei jemandem)', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kotaeru', kana: 'こたえる', written: '答える', meaningDe: 'antworten', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_tanomu', kana: 'たのむ', written: '頼む', meaningDe: 'bitten um', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kimeru', kana: 'きめる', written: '決める', meaningDe: 'entscheiden', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_yobu', kana: 'よぶ', written: '呼ぶ', meaningDe: 'rufen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_sagasu', kana: 'さがす', written: '探す', meaningDe: 'suchen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_mitsukeru', kana: 'みつける', written: '見つける', meaningDe: 'finden', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_nakusu', kana: 'なくす', meaningDe: 'verlieren', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_tetsudau', kana: 'てつだう', written: '手伝う', meaningDe: 'helfen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_ganbaru', kana: 'がんばる', meaningDe: 'sich anstrengen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_isogu', kana: 'いそぐ', written: '急ぐ', meaningDe: 'sich beeilen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_hajimaru', kana: 'はじまる', written: '始まる', meaningDe: 'beginnen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_hajimeru', kana: 'はじめる', written: '始める', meaningDe: 'anfangen mit', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_owaru', kana: 'おわる', written: '終わる', meaningDe: 'enden', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_sumu', kana: 'すむ', written: '住む', meaningDe: 'wohnen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_iru', kana: 'いる', meaningDe: 'da sein (Lebewesen)', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_aru', kana: 'ある', meaningDe: 'da sein (Dinge), haben', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_naru', kana: 'なる', meaningDe: 'werden', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_suru', kana: 'する', meaningDe: 'machen, tun', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_dekiru', kana: 'できる', meaningDe: 'können', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_shinu', kana: 'しぬ', written: '死ぬ', meaningDe: 'sterben', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_nakunaru', kana: 'なくなる', written: '亡くなる', meaningDe: 'versterben', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_umareru', kana: 'うまれる', written: '生まれる', meaningDe: 'geboren werden', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_naku', kana: 'なく', written: '泣く', meaningDe: 'weinen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_warau', kana: 'わらう', written: '笑う', meaningDe: 'lachen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_okoru', kana: 'おこる', written: '怒る', meaningDe: 'sich ärgern', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_komaru', kana: 'こまる', written: '困る', meaningDe: 'in Not sein', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_tsukareru', kana: 'つかれる', written: '疲れる', meaningDe: 'müde werden', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_furu', kana: 'ふる', written: '降る', meaningDe: 'fallen (Regen, Schnee)', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_fuku_blow', kana: 'ふく', written: '吹く', meaningDe: 'wehen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_hareru', kana: 'はれる', written: '晴れる', meaningDe: 'aufklaren', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kieru', kana: 'きえる', written: '消える', meaningDe: 'verschwinden', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_tsukeru', kana: 'つける', meaningDe: 'anschalten', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kesu', kana: 'けす', written: '消す', meaningDe: 'ausschalten, löschen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_hiku', kana: 'ひく', written: '引く', meaningDe: 'ziehen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_osu', kana: 'おす', written: '押す', meaningDe: 'drücken', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_ugoku', kana: 'うごく', written: '動く', meaningDe: 'sich bewegen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_tobu', kana: 'とぶ', written: '飛ぶ', meaningDe: 'fliegen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_noboru', kana: 'のぼる', written: '登る', meaningDe: 'hinaufsteigen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_sanpo_suru', kana: 'さんぽする', written: '散歩する', meaningDe: 'spazieren gehen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_denwa_suru', kana: 'でんわする', written: '電話する', meaningDe: 'anrufen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_abiru', kana: 'あびる', written: '浴びる', meaningDe: 'duschen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_migaku', kana: 'みがく', written: '磨く', meaningDe: 'putzen (Zähne)', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_suu', kana: 'すう', written: '吸う', meaningDe: 'rauchen, einatmen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_saku', kana: 'さく', written: '咲く', meaningDe: 'blühen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_yameru', kana: 'やめる', meaningDe: 'aufhören', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_okureru', kana: 'おくれる', written: '遅れる', meaningDe: 'sich verspäten', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_maniau', kana: 'まにあう', written: '間に合う', meaningDe: 'rechtzeitig kommen', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kakaru', kana: 'かかる', meaningDe: 'dauern, kosten', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_kekkon_suru', kana: 'けっこんする', written: '結婚する', meaningDe: 'heiraten', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
  PoolEntry(id: 'lex_ja_chigau', kana: 'ちがう', written: '違う', meaningDe: 'anders sein, falsch sein', pos: PartOfSpeech.verb, domain: VocabDomain.verbenAlltag),
];
