//
// Wortvorrat 800, Liste B: Café, Essen, Einkaufen, Kleidung.
// Quelle: Plan docs/superpowers/plans/2026-09-18-wortvorrat-800.md, Task 4.

import 'pool_entry.dart';

const List<PoolEntry> vocabPoolJaCafeEinkaufen = [
  PoolEntry(id: 'lex_ja_koohii', kana: 'コーヒー', meaningDe: 'Kaffee', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_ocha', kana: 'おちゃ', written: 'お茶', meaningDe: 'Tee', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_koucha', kana: 'こうちゃ', written: '紅茶', meaningDe: 'Schwarztee', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_water', kana: 'みず', written: '水', meaningDe: 'Wasser', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_oyu', kana: 'おゆ', written: 'お湯', meaningDe: 'heißes Wasser', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_gyuunyuu', kana: 'ぎゅうにゅう', written: '牛乳', meaningDe: 'Milch', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_juusu', kana: 'ジュース', meaningDe: 'Saft', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_biiru', kana: 'ビール', meaningDe: 'Bier', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_sake', kana: 'さけ', written: '酒', meaningDe: 'Sake, Alkohol', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_pan', kana: 'パン', meaningDe: 'Brot', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_gohan', kana: 'ごはん', written: 'ご飯', meaningDe: 'Reis, Essen', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_asagohan', kana: 'あさごはん', written: '朝ご飯', meaningDe: 'Frühstück', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_hirugohan', kana: 'ひるごはん', written: '昼ご飯', meaningDe: 'Mittagessen', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_bangohan', kana: 'ばんごはん', written: '晩ご飯', meaningDe: 'Abendessen', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_tabemono', kana: 'たべもの', written: '食べ物', meaningDe: 'Essen, Lebensmittel', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_nomimono', kana: 'のみもの', written: '飲み物', meaningDe: 'Getränk', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_tamago', kana: 'たまご', written: '卵', meaningDe: 'Ei', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_sakana', kana: 'さかな', written: '魚', meaningDe: 'Fisch', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_niku', kana: 'にく', written: '肉', meaningDe: 'Fleisch', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_yasai', kana: 'やさい', written: '野菜', meaningDe: 'Gemüse', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_kudamono', kana: 'くだもの', written: '果物', meaningDe: 'Obst', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_ringo', kana: 'りんご', meaningDe: 'Apfel', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_mikan', kana: 'みかん', meaningDe: 'Mandarine', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_banana', kana: 'バナナ', meaningDe: 'Banane', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_satou', kana: 'さとう', written: '砂糖', meaningDe: 'Zucker', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_shio', kana: 'しお', written: '塩', meaningDe: 'Salz', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_okashi', kana: 'おかし', written: 'お菓子', meaningDe: 'Süßigkeiten', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_keeki', kana: 'ケーキ', meaningDe: 'Kuchen', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_karee', kana: 'カレー', meaningDe: 'Curry', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_raamen', kana: 'ラーメン', meaningDe: 'Ramen', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_soba', kana: 'そば', meaningDe: 'Soba-Nudeln', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_udon', kana: 'うどん', meaningDe: 'Udon-Nudeln', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_sushi', kana: 'すし', meaningDe: 'Sushi', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_tenpura', kana: 'てんぷら', meaningDe: 'Tempura', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_toufu', kana: 'とうふ', written: '豆腐', meaningDe: 'Tofu', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_misoshiru', kana: 'みそしる', written: 'みそ汁', meaningDe: 'Misosuppe', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_onigiri', kana: 'おにぎり', meaningDe: 'Reisbällchen', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_obentou', kana: 'おべんとう', written: 'お弁当', meaningDe: 'Lunchbox', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_chiizu', kana: 'チーズ', meaningDe: 'Käse', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_bataa', kana: 'バター', meaningDe: 'Butter', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_aisukuriimu', kana: 'アイスクリーム', meaningDe: 'Eiscreme', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_ryouri', kana: 'りょうり', written: '料理', meaningDe: 'Gericht, Kochen', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_menyuu', kana: 'メニュー', meaningDe: 'Speisekarte', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_koppu', kana: 'コップ', meaningDe: 'Glas (Trinkglas)', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_kappu', kana: 'カップ', meaningDe: 'Tasse', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_osara', kana: 'おさら', written: 'お皿', meaningDe: 'Teller', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_hashi_chopsticks', kana: 'はし', written: '箸', meaningDe: 'Essstäbchen', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_supuun', kana: 'スプーン', meaningDe: 'Löffel', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_fooku', kana: 'フォーク', meaningDe: 'Gabel', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_naifu', kana: 'ナイフ', meaningDe: 'Messer', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_teeburu', kana: 'テーブル', meaningDe: 'Tisch', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_resutoran', kana: 'レストラン', meaningDe: 'Restaurant', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_kissaten', kana: 'きっさてん', written: '喫茶店', meaningDe: 'Café', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_shokudou', kana: 'しょくどう', written: '食堂', meaningDe: 'Kantine, Lokal', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_aji', kana: 'あじ', written: '味', meaningDe: 'Geschmack', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_koori', kana: 'こおり', written: '氷', meaningDe: 'Eis (gefroren)', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_tabako', kana: 'たばこ', meaningDe: 'Zigarette', pos: PartOfSpeech.nomen, domain: VocabDomain.cafe),
  PoolEntry(id: 'lex_ja_okane', kana: 'おかね', written: 'お金', meaningDe: 'Geld', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_nedan', kana: 'ねだん', written: '値段', meaningDe: 'Preis', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_mise', kana: 'みせ', written: '店', meaningDe: 'Laden', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen, plannedEpisode: 1, status: PoolStatus.ausgeliefert),
  PoolEntry(id: 'lex_ja_kaimono', kana: 'かいもの', written: '買い物', meaningDe: 'Einkauf', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_depaato', kana: 'デパート', meaningDe: 'Kaufhaus', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_suupaa', kana: 'スーパー', meaningDe: 'Supermarkt', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_konbini', kana: 'コンビニ', meaningDe: 'Minimarkt', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_honya', kana: 'ほんや', written: '本屋', meaningDe: 'Buchladen', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_yaoya', kana: 'やおや', written: '八百屋', meaningDe: 'Gemüseladen', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_nikuya', kana: 'にくや', written: '肉屋', meaningDe: 'Metzgerei', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_sakanaya', kana: 'さかなや', written: '魚屋', meaningDe: 'Fischladen', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_panya', kana: 'パンや', written: 'パン屋', meaningDe: 'Bäckerei', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_hanaya', kana: 'はなや', written: '花屋', meaningDe: 'Blumenladen', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_kusuriya', kana: 'くすりや', written: '薬屋', meaningDe: 'Apotheke', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_otsuri', kana: 'おつり', written: 'お釣り', meaningDe: 'Wechselgeld', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_reji', kana: 'レジ', meaningDe: 'Kasse', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_fukuro', kana: 'ふくろ', written: '袋', meaningDe: 'Tüte', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_saifu', kana: 'さいふ', written: '財布', meaningDe: 'Geldbeutel', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_kaado', kana: 'カード', meaningDe: 'Karte', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_reshiito', kana: 'レシート', meaningDe: 'Kassenbon', pos: PartOfSpeech.nomen, domain: VocabDomain.einkaufen),
  PoolEntry(id: 'lex_ja_fuku', kana: 'ふく', written: '服', meaningDe: 'Kleidung', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung),
  PoolEntry(id: 'lex_ja_shatsu', kana: 'シャツ', meaningDe: 'Hemd', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung),
  PoolEntry(id: 'lex_ja_zubon', kana: 'ズボン', meaningDe: 'Hose', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung),
  PoolEntry(id: 'lex_ja_sukaato', kana: 'スカート', meaningDe: 'Rock', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung),
  PoolEntry(id: 'lex_ja_seetaa', kana: 'セーター', meaningDe: 'Pullover', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung),
  PoolEntry(id: 'lex_ja_kooto', kana: 'コート', meaningDe: 'Mantel', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung),
  PoolEntry(id: 'lex_ja_kutsu', kana: 'くつ', written: '靴', meaningDe: 'Schuhe', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung),
  PoolEntry(id: 'lex_ja_kutsushita', kana: 'くつした', written: '靴下', meaningDe: 'Socken', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung),
  PoolEntry(id: 'lex_ja_boushi', kana: 'ぼうし', written: '帽子', meaningDe: 'Hut, Mütze', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung),
  PoolEntry(id: 'lex_ja_kaban', kana: 'かばん', meaningDe: 'Tasche', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung),
  PoolEntry(id: 'lex_ja_poketto', kana: 'ポケット', meaningDe: 'Tasche (an Kleidung)', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung),
  PoolEntry(id: 'lex_ja_hankachi', kana: 'ハンカチ', meaningDe: 'Taschentuch', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung),
  PoolEntry(id: 'lex_ja_megane', kana: 'めがね', written: '眼鏡', meaningDe: 'Brille', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung),
  PoolEntry(id: 'lex_ja_tokei', kana: 'とけい', written: '時計', meaningDe: 'Uhr', pos: PartOfSpeech.nomen, domain: VocabDomain.dinge),
  PoolEntry(id: 'lex_ja_kasa', kana: 'かさ', written: '傘', meaningDe: 'Schirm', pos: PartOfSpeech.nomen, domain: VocabDomain.kleidung, plannedEpisode: 1, status: PoolStatus.ausgeliefert),
];
